### ISSUE TITLE
tallo - If a module is removed by the controller after calling lock() it will result in a complete bricking of the SetToken contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#107]
tallo

medium

# If a module is removed by the controller after calling lock() it will result in a complete bricking of the SetToken contract

## Summary
Modules that call ```lock()``` in ```SetToken.sol``` will be unable to call ```unlock()``` if they are removed as a module by the controller. This results in all the functionality behind the ```whenLockedOnlyLocker``` modifier being permanently locked since only the locker has permission to call ```unlock()```.

## Vulnerability Detail
The ```lock()``` function inside ```SetToken.sol``` allows modules to be designated as the ```locker``` and lock certain important functionality until they call ```unlock()```.
```solidity
    function lock() external onlyModule {
        require(!isLocked, "Must not be locked");
        locker = msg.sender;
        isLocked = true;
    }
```

If the module were to be removed in ```Controller.sol``` by the owner after ```lock()``` was just called then the module will no longer be registered.
```solidity
    function removeModule(address _module) external onlyInitialized onlyOwner {
        require(isModule[_module], "Module does not exist");

        modules = modules.remove(_module);

        //@audit here isModule is set to false
        isModule[_module] = false;

        emit ModuleRemoved(_module);
    }
```
When the module is no longer registered, it is no longer able to call functions behind the onlyModule modifier since ```controller#isModule(msg.sender)``` will return false.
```solidity
    modifier onlyModule() {
        _validateOnlyModule();
        _;
    }

    function _validateOnlyModule() internal view {
       //..
        require(
            controller.isModule(msg.sender),
            "Module must be enabled on controller"
        );
    }

```
This means that ```unlock()``` can't be called by anybody since it requires both ```onlyModule``` to not revert and ```locker``` to be equal to ```msg.sender```

```solidity
    function unlock() external onlyModule {
        require(isLocked, "Must be locked");
        require(locker == msg.sender, "Must be locker");
        delete locker;
        isLocked = false;
    }
```
## Impact
All key protocol functionality such as ```invoke()```, ```mint()```, ```burn()```, etc... will be blocked and rendered useless. Furthermore, simply re-adding and re-initializing the module to ```Controller.sol``` and ```SetToken.sol```  to call ```unlock()``` is not possible since ```initializeModule()``` requires that the protocol is not locked.

```solidity
//@audit SetToken.sol
   function initializeModule() external {
        require(!isLocked, "Only when unlocked");
```

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetToken.sol#L343
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetToken.sol#L684
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetToken.sol#L352
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/Controller.sol#L235

## Tool used

Manual Review

## Recommendation
Managers should have the ability to emergency unlock the protocol

**Comment by talllo** [comment]
Escalate for 10 USDC
I believe this issue was unjustly excluded. Considering that there could be be hundreds of public or private SetToken contracts, it is a reasonable assumption that atleast one could encounter this scenario and end up losing all their funds locked in the contract. #286 further expands on the same issue to include to include faulty/malicious modules.

**Comment by 0xffff11** [comment]
Seems like there as to be some admin mistake for this to happen. Would like @talllo to confirm, how feasable this actually is, if it is at all

**Comment by talllo** [comment]
Its pretty unlikely, especially at the moment because no modules currently make use of the lock/unlock feature. however i think its a reasonable assumption that a future module will use it. 
Heres a few plausible scenarios where this issue could come up:
1. a module is recalled for an update by the owners which results in them calling ```removeModule``` on the old module and then adding the new module. All SetTokens that were locked would be bricked. the locking period being indefinite (days, weeks, or months especially on the publicly used SetTokens) increases the odds. No admin mistakes required here because, besides the bug, this is an intended protocol use case.
2. as #286 points out, a compromised or buggy module that attains a lock and never releases it.

Considering that there could be hundreds or thousands of public/private SetTokens in existence (1) is probably the most likely

**Comment by talllo** [comment]
Update: 
https://github.com/IndexCoop/index-protocol/blob/663e64efaa95df2247afa8926d4cfb42948f54fe/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol
The updated audit contest adds the ```AuctionRebalanceModuleV1.sol``` module which makes use of the lock/unlock functionality during an arbitrary length rebalance period

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Given the admin is trusted with the function call flow. 
Set-Token manager is trusted to manage modules on the SetToken.
This requires admin error to remove a module whose set token is not unlocked.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [talllo](https://github.com/sherlock-audit/2023-05-Index-judging/issues/107/#issuecomment-1610142672): rejected

**Comment by talllo** [comment]
With all due respect I think you're wrong here @hrishibhat . Admin error is not required here. The SetToken manager can only add/remove modules that are set by the controller.
```solidity
    function addModule(address _module) external onlyManager {
        require(moduleStates[_module] == ISetToken.ModuleState.NONE, "Module must not be added");
        //@audit checks that the controller enables it
        require(controller.isModule(_module), "Must be enabled on Controller");
```
What i am pointing out is not an error by the SetToken manager, but a normal functionality use case by the Controller manager that has consequences for SetToken users. I'm saying if the controller calls removeModule in the Controller.sol contract, it will have consequences on vulnerable SetTokens. Again, no manager or admin error is required here, this is a valid and normal use-case that the Controller is designed for and the SetToken manager is not involved in any aspect of this

**Comment by hrishibhat** [comment]
The removeModule is still an admin function, removing a module can be considered an important function and not a regular action. Necessary precautions must be taken by the admin to make sure the respective settoken is not affected adversely. 
As per the rule any loss caused by this is still and admin error.

**Comment by ckoopmann** [comment]
Assuming that the Manager has to trigger a `lock` and then call `removeModule` for this to arise, this should be considered admin error.

However I agree that it could be that the Controller could `remove` a module from the module list leading to the module being unable to unlock the respective token unless the Controller reenables it.
This situation could arise due to a lack of communcation between those two roles, even though it can be remediated by the Controller reenabling it, therefore the token should not be "permanently" bricked. 

For now I don't think we will be adding a fix for this as it can be avoided / remediated by the controller making sure that no set token is locked by a given module before removing that module from the protocol. 
However this is a valuable issue and will inform our behaviour when operating the protocol.

I defer to the lead watson / judge to decide on validity / severity.

**Comment by pblivin0x** [comment]
The `Controller.removeSet()` method is an unfortunate inclusion in Set V2 and has remained in Index Coop's fork of the protocol. It exposes SetToken manager's to centralization risk from the Controller owner. 

The SetToken manager is also exposed to Controller owner centralization risk via`Controller.removeModule()` and `Controller.removeResource()`.

These issues will likely not be changed in the already aged protocol.
