### ISSUE TITLE
jasonxiale - AaveV3LeverageModule.lever might failed to update default position when using SWAP_TOKENS_FOR_EXACT_TOKENS trade

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#119]
jasonxiale

medium

# AaveV3LeverageModule.lever might failed to update default position when using SWAP_TOKENS_FOR_EXACT_TOKENS trade

## Summary
While calling `AaveV3LeverageModule.delever` and `AaveV3LeverageModule.deleverToZeroBorrowBalance` the functions call  [AaveV3LeverageModule._updateDeleverPositions](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#LL878C76-L878C87) to update the positions, within `AaveV3LeverageModule._updateDeleverPositions` [AaveV3LeverageModule.sol#L880-L887](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L880-L887) is used to handle over-pay assets.

Similar issue might happen in `AaveV3LeverageModule.lever` if  `exact output swaps` is used, in such case, the remaining asset is not accounted as default position

## Vulnerability Detail
[AaveV3LeverageModule._executeTrade](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L794) is used to swap tokens.

[Line 816](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L816) calls `exchangeAdapter.getTradeCalldata` to pack trade data, `UniswapV2ExchangeAdapterV2.getTradeCalldata` is one of the exhange adaptor.

According to [UniswapV2ExchangeAdapterV2.getTradeCalldata](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/integration/exchange/UniswapV2ExchangeAdapterV2.sol#L74-L100), the last byte of **_data** is used to determine `SWAP_EXACT_TOKENS_FOR_TOKENS` or `SWAP_TOKENS_FOR_EXACT_TOKENS`
```solidity
    function getTradeCalldata(
        address /* _sourceToken */,
        address /* _destinationToken */,
        address _destinationAddress,
        uint256 _sourceQuantity,
        uint256 _destinationQuantity,
        bytes memory _data
    )
        external
        view
        returns (address, uint256, bytes memory)
    {
        (
            address[] memory path,
            bool shouldSwapExactTokensForTokens
        ) = abi.decode(_data, (address[],bool));

        bytes memory callData = abi.encodeWithSignature(
            shouldSwapExactTokensForTokens ? SWAP_EXACT_TOKENS_FOR_TOKENS : SWAP_TOKENS_FOR_EXACT_TOKENS,
            shouldSwapExactTokensForTokens ? _sourceQuantity : _destinationQuantity,
            shouldSwapExactTokensForTokens ? _destinationQuantity : _sourceQuantity,
            path,
            _destinationAddress,
            block.timestamp
        );
        return (router, 0, callData);
    }
```

If `SWAP_TOKENS_FOR_EXACT_TOKENS` is used, after calling `_executeTrade` in [lever](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L279), there might some assets left which should accounted for updating the default position 

## Tool used

Manual Review

## Recommendation
Using similar function as `_updateDeleverPositions._updateDeleverPositions`

**Comment by crazy4linux** [comment]
Escalate for 10 USDC

This is a valid issue since [UniswapV2ExchangeAdapterV2.getTradeCalldata](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/integration/exchange/UniswapV2ExchangeAdapterV2.sol#L74-L100) is a valid(in-use) exchanger, and within the last byte means SWAP_EXACT_TOKENS_FOR_TOKENS or SWAP_TOKENS_FOR_EXACT_TOKENS

**Comment by Evert0x** [comment]
Not really clear to me how this affects a user in the protocol.

@0xffff11 what do you think about this issue?

**Comment by crazy4linux** [comment]
The previous audit issue "5.5.1 Unaccounted positions after deleverage (high risk)" is caused by over-pay the debt, which results in the remaining assert becomes unaccounted.
Similar in above report, if the "SWAP_EXACT_TOKENS_FOR_TOKENS" type swapped is used, I think it's also possible there might be some remaining assets left in the protocol, and could become unaccounted.

**Comment by ckoopmann** [comment]
This issue is technically correct. However there is no reason to ever use an `exactOutput` swap in this context and it will be up to the Operator to make sure the correct trade data is configured.
Therefore we will not implement a smart contract fix for this but instead rely on the Operator to only use `exactInput` swaps here.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low issue since operator is trusted to use appropriate swaps. Agree with Sponsor's comment above

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [crazy4linux](https://github.com/sherlock-audit/2023-05-Index-judging/issues/119/#issuecomment-1613201932): rejected
