### ISSUE TITLE
ast3ros - BaseManagerV2 lacks function to remove pending module

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#131]
ast3ros

medium

# BaseManagerV2 lacks function to remove pending module

## Summary

The SetToken contract has a function called `removePendingModule` that can only be invoked by its manager. However, if the manager is set to be the BaseManagerV2 contract, this function becomes inaccessible because BaseManagerV2 does not have a corresponding function to call it.

## Vulnerability Detail

The `removePendingModule` function in the SetToken contract allows the manager to remove a module that is in the pending state.

        function removePendingModule(address _module) external onlyManager {}

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetToken.sol#L392

However, if the manager is set to be the `BaseManagerV2` contract, this function cannot be invoked. This is because BaseManagerV2 does not have a function that can interact with the `removePendingModule` function of the SetToken contract.

## Impact

The inability to remove a pending module may affect the functionality and security of the SetToken contract.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetToken.sol#L392

## Tool used

Manual Review

## Recommendation

Implement a function in BaseManagerV2 that can call the `removePendingModule` function of the SetToken contract. For example:

```javascript
    function removePendingModule(address _module) external onlyOperator {
        setToken.removePendingModule(_module);
    }
```

**Comment by thangtranth** [comment]
Escalate for 10 USDC

removePendingModule functionality will not work and no pending module can be removed if BaseManagerV2 is the manager.  Please help to review.

**Comment by Evert0x** [comment]
Seems like a duplicate of #135

**Comment by thangtranth** [comment]
Hi Evert, 

My original intention to split the missing interface into 2 issues was because:

- #131 would mention the missing interface in BaseManagerV2
- #135 would mention the missing interface in AaveLeverageStrategyExtension.

However, due to my careless mistake, I also wrote about BaseManagerV2 in #135. I apologize for the confusion.

---

As we know the the manager is always to be set to BaseManagerV2 contract. 

https://discord.com/channels/812037309376495636/1109133391904915557/1111458020329787525

Therefore, BaseManagerV2 should be able to remove pending module, but it cannot do so. 
It is worth noting that the BaseManagerV2 has all other functions addModule, removeModule, protectModule. It lacks the only function `removePendingModule`.

https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/README.md?plain=1#L50

**Comment by hrishibhat** [comment]
Result:
Low
Unique
While there is no `removePendingModule` in baseManager , this seems more like an additional feature to remove a non initialized module. Since all modules are trusted contracts, added and controlled by the protocol, don't see a medium impact of this issue. There are ways to still remove the module.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thangtranth](https://github.com/sherlock-audit/2023-05-Index-judging/issues/131/#issuecomment-1610608473): rejected
