### ISSUE TITLE
ast3ros - BaseManagerV2 lacks interface to interact with module functions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#135]
ast3ros

medium

# BaseManagerV2 lacks interface to interact with module functions

## Summary

Modules have functions that can only be invoked by the manager of the SetToken. However, if the manager is set to be the BaseManagerV2 contract, these functions become inaccessible because BaseManagerV2 does not have a corresponding interface to call them.

## Vulnerability Detail

The AaveV3LeverageModule has functions such as `initialize`, `registerToModule`, `addCollateralAssets`, `removeCollateralAssets`, `addBorrowAssets`, and `removeBorrowAssets` that are restricted to the manager of the SetToken.

However, if the manager is set to be the BaseManagerV2 contract, these functions cannot be invoked. This is because BaseManagerV2 does not have an interface to interact with these functions of the AaveV3LeverageModule.

The functionality of the module will be halted until the manager is changed to another address such as an EOA or a contract with sufficient functions to call those.

## Impact

The lack of interface may affect the functionality and security of the modules such as AaveV3LeverageModule and the SetToken.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L485
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L552
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L598
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L607
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L627
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L637

## Tool used

Manual Review

## Recommendation

Implement interfaces in BaseManagerV2 or an extension contract that can call these functions of the AaveV3LeverageModule. The same approach is already applied to the `setEModeCategory` function when it is implemented in the AaveV3LeverageStrategyExtension extension.

**Comment by thangtranth** [comment]
Escalate for 10 USDC

By using BaseManagerV2, many functionalities cannot be used. Please help to review.

**Comment by Evert0x** [comment]
@thangtranth seems like a valid issue in case the protocol team intends to deploy as described. Can you provide a resource that shows this intention? E.g. link to a code comment.

**Comment by thangtranth** [comment]
Hi @Evert0x, 

You can find it here in sponsor's comment in public channel:
- The manager is always to be set to BaseManagerV2 contract.

![image](https://github.com/sherlock-audit/2023-05-Index-judging/assets/60476800/528a46b1-05c9-4f66-b4a5-0a3c2ebc92f3)

https://discord.com/channels/812037309376495636/1109133391904915557/1111458020329787525

---

I reviewed it again and I apologize for my mistake in the original writing. The root cause is still the lack of interface for those above mentioned functions “initialize, registerToModule, addCollateralAssets, removeCollateralAssets, addBorrowAssets, and removeBorrowAssets”.

However, what I mean is: the interface is missing in `AaveLeverageStrategyExtension`, not in `BaseManagerV2`. 

The `BaseManagerV2` has a function `interactManager` that allows the extension to call any function in the module. The call graph is:

- Extension -> BaseManagerV2 (interactManager) -> Module.

https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/manager/BaseManagerV2.sol#L300-L307

Therefore, if an extension has those functions, it can act as the manager and call the module functions.

However, the AaveLeverageStrategyExtension does not have those functions. So in current setup, those functions are inaccessible.

I am really sorry for my mistake.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Although do not see an medium impact of not being able to use these functions and as pointed out,
> The functionality of the module will be halted until the manager is changed to another address such as an EOA or a contract with sufficient functions to call those.

Based on these considering this issue a low.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thangtranth](https://github.com/sherlock-audit/2023-05-Index-judging/issues/135/#issuecomment-1610604979): rejected
