### ISSUE TITLE
Saeedalipoor01988 - LastTradeTimestamp value for exchange is not updated in the disengage function.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#183]
Saeedalipoor01988

medium

# LastTradeTimestamp value for exchange is not updated in the disengage function.

## Summary
The [globalLastTradeTimestamp and exchangeLastTradeTimestamp](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1207) values don't update in the [disengage ](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L412)function.

## Vulnerability Detail

```solidity
     function _updateLastTradeTimestamp(string memory _exchangeName) internal {
        globalLastTradeTimestamp = block.timestamp;
        exchangeSettings[_exchangeName].exchangeLastTradeTimestamp = block.timestamp;
     }

```
This function updates both the exchange-specific and global timestamp so that the epoch rebalance can use the global timestamp (since the global timestamp is always equal to the most recently used exchange timestamp). This allows for multiple rebalances to occur simultaneously since only the exchange-specific timestamp is checked for non-epoch rebalances.

Before any trade execution, this function gets called in ripcord, iterateRebalance, rebalance and engage functions to update both the exchange-specific and global timestamp.

But in the [disengage ](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L412)function, trade execution get done without update LastTradeTimestamp for the exchange-specific and global timestamp.

**What this means for investors: the TWAP Cooldown Period allows time for the relevant liquidity pools that the FLI contracts trade against during rebalancing to absorb the most recent rebalance transaction before submitting a subsequent one. Allowing the liquidity pool to rebalance after each trade shields FLI products from unfavorable slippage, minimizing operational costs and preserving AUM.**

https://docs.indexcoop.com/index-coop-community-handbook/products/flexible-leverage-indices/fli-technical-documentation/fli-product-parameters#twap-cooldown-period

## Impact
Please check the Vulnerability Detail.

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L412
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1207

## Tool used
Manual Review

## Recommendation
Update globalLastTradeTimestamp and exchangeLastTradeTimestamp values before the trade.

**Comment by saeedalipoorcom** [comment]
Escalate for 10 USDC

From [From docs.indexcoop.com](https://docs.indexcoop.com/index-coop-community-handbook/products/flexible-leverage-indices/fli-technical-documentation/fli-product-parameters#twap-cooldown-period)  :

`The TWAP Cooldown Period (TWAP: Total Weighted Average Price) specifies the amount of time that FLI contracts must wait to initiate another rebalance transaction. The unit of measure for the Cooldown Period is seconds and it is compared to the timestamp of the last transaction. Delaying consecutive rebalance transactions allows the liquidity pool to be arbitraged back to the correct price before placing the next trade, which has a favorable effect on price impact and slippage for the relative liquidity pools.`

The unit of measure for the Cooldown Period is seconds and **_it is compared to the timestamp of the last transaction made with the DEX_**, for [_lever process](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L277) and [_delever process](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L388C9-L388C17).

For _lever process, AaveLeverageStrategyExtension.sol is using _updateRebalanceState function to call _updateLastTradeTimestamp(_exchangeName).

```
    function _updateRebalanceState(
        uint256 _chunkRebalanceNotional,
        uint256 _totalRebalanceNotional,
        uint256 _newLeverageRatio,
        string memory _exchangeName
    )
        internal
    {

        **_updateLastTradeTimestamp(_exchangeName);**

        if (_chunkRebalanceNotional < _totalRebalanceNotional) {
            twapLeverageRatio = _newLeverageRatio;
        }
    }
```
And for _delever process, AaveLeverageStrategyExtension.sol is using _updateRipcordState function to call _updateLastTradeTimestamp(_exchangeName).

```
    function _updateRipcordState(string memory _exchangeName) internal {

        **_updateLastTradeTimestamp(_exchangeName);**

        // If TWAP leverage ratio is stored, then clear state. This may happen if we are currently in a TWAP rebalance, and the leverage ratio moves above the
        // incentivized threshold for ripcord.
        if (twapLeverageRatio > 0) {
            delete twapLeverageRatio;
        }
    }
```

Now in the in the [disengage function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L426), if totalRebalanceNotional value is more than chunkRebalanceNotional value , AaveLeverageStrategyExtension.sol will calls to the _delever function. but there is not update on _updateLastTradeTimestamp(_exchangeName).

```
        if (totalRebalanceNotional > chunkRebalanceNotional) {
            _delever(leverageInfo, chunkRebalanceNotional);
        } else {
            _deleverToZeroBorrowBalance(leverageInfo, totalRebalanceNotional);
        }

        emit Disengaged(
            leverageInfo.currentLeverageRatio,
            newLeverageRatio,
            chunkRebalanceNotional,
            totalRebalanceNotional
        );
```

What is impact ? [From docs.indexcoop.com](https://docs.indexcoop.com/index-coop-community-handbook/products/flexible-leverage-indices/fli-technical-documentation/fli-product-parameters#twap-cooldown-period) :
There is not protection from unfavorable slippage, minimizing operational costs and preserving AUM.

**Comment by saeedalipoorcom** [comment]
Escalate for 10 USDC

According to the explanation of the team member in the link below:
https://github.com/sherlock-audit/2023-05-Index-judging/issues/265#issuecomment-1601093094

functions rebalance(), iterateRebalance(), ripcord() will be inaccessible because of this check, ([see check](https://github.com/IndexCoop/index-coop-smart-contracts/blob/317dfb677e9738fc990cf69d198358065e8cb595/contracts/adapters/AaveLeverageStrategyExtension.sol#L867)).

```solidity
require(actionInfo.borrowBalance > 0, "Borrow balance must exist");
rebalanceInfo.borrowBalance = strategy.targetBorrowDebtToken.balanceOf(address(strategy.setToken));
```

In the scenario that disengage function calls the _deleverToZeroBorrowBalance function, AaveV3LeverageModule contract will try to performs a DEX trade, exchanging the _collateralAsset for _repayAsset and in this DEX trade, Minimum receive amount is set to the current variable debt balance of the borrow asset. 

But please consider this point, **_In Aave, both collateral and borrow interest is accrued in each block by increasing the balance of aTokens and debtTokens._**

The problem is that AaveV3LeverageModule contract is performing a DEX trade that deadline check by default is block.timestamp–this basically disables the transaction expiration check because the deadline will be set to whatever timestamp the block including the transaction is minted at.

So, DEX trade can gets done 3 blocks later and after this 3 blocks, Aave borrow interest is accrued for more 3 blocks. So it is possible that after fully repaid the loan by disengage._deleverToZeroBorrowBalance() function, the targetBorrowDebtToken balance for setToken will still be greater than zero.

T1 :

- The operator calls disengage function to fully repay the loan for debtToken.
- If chunk rebalance size is above max borrow or max trade size, [_deleverToZeroBorrowBalance function](https://github.com/IndexCoop/index-coop-smart-contracts/blob/317dfb677e9738fc990cf69d198358065e8cb595/contracts/adapters/AaveLeverageStrategyExtension.sol#L429) will gets called.
- The [AaveV3LeverageModule.sol contract](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L393) will get variableDebtToken.balanceOf(address(_setToken)) to use as Minimum receive amount for the DEX trade. AaveV3LeverageModule.sol contract assumes that this is all the debt that must be paid.
- [DEX trade will gets done with deadline check by default is block.timestamp](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/integration/exchange/UniswapV2ExchangeAdapter.sol#L90), this basically disables the transaction expiration check because the deadline will be set to whatever timestamp the block including the transaction is minted at.

The trade transaction can be pending in mempool and be done 5 blocks later. according to AAVE Document,  **_In Aave, both collateral and borrow interest is accrued in each block by increasing the balance of aTokens and debtTokens._**, so variableDebtToken.balanceOf(address(_setToken)) in T5 ,is more than T1.

T5 :

- The AaveV3LeverageModule.sol contract, paid the total debt minus 5 blocks.

Now [this check](https://github.com/IndexCoop/index-coop-smart-contracts/blob/317dfb677e9738fc990cf69d198358065e8cb595/contracts/adapters/AaveLeverageStrategyExtension.sol#L867) can be easily broken. and because of there was not update on [_updateLastTradeTimestamp(_exchangeName)](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1207), [From docs.indexcoop.com](https://docs.indexcoop.com/index-coop-community-handbook/products/flexible-leverage-indices/fli-technical-documentation/fli-product-parameters#twap-cooldown-period) :
There is not protection from unfavorable slippage, minimizing operational costs and preserving AUM to the User.

**Comment by Evert0x** [comment]
The original issue submission is missing a clear description how the said vulnerability impacts the protocol, a lot of context has been added in the escalation. 

@0xffff11 what do you think about the escalation comment? Does it describe a valid issue?

**Comment by 0xsuren** [comment]
> The original issue submission is missing a clear description how the said vulnerability impacts the protocol, a lot of context has been added in the escalation.
> 
> @0xffff11 what do you think about the escalation comment? Does it describe a valid issue?

I added more explanations to prove the correctness of the issue I found. If my explanation is wrong, I respect your decision 🙂.

What this means for investors: **the TWAP Cooldown Period allows time for the relevant liquidity pools that the FLI contracts trade against during rebalancing to absorb the most recent rebalance transaction before submitting a subsequent one. Allowing the liquidity pool to rebalance after each trade shields FLI products from unfavorable slippage, minimizing operational costs and preserving AUM.**

i think this is clear how vulnerability impacts the protocol ? 🧐 🧐 🧐 🙏

**Comment by ckoopmann** [comment]
Seems to be a duplicate of:
https://github.com/sherlock-audit/2023-05-Index-judging/issues/265

**Comment by 0xffff11** [comment]
> The original issue submission is missing a clear description how the said vulnerability impacts the protocol, a lot of context has been added in the escalation.
> 
> @0xffff11 what do you think about the escalation comment? Does it describe a valid issue?

I also think this is a dup of #265

**Comment by ckoopmann** [comment]
1. Not sure about what the actual impact is supposed to be here. Watson writes _Allowing the liquidity pool to rebalance after each trade shields FLI products from unfavorable slippage, minimizing operational costs and preserving AUM_  - where is the problem
2. `The trade transaction can be pending in mempool and be done 5 blocks later.` - Don't quite understand this. The operator just keeps calling `disengage`. The calculation of the amounts to be traded / repayed and the trades are in the same transaction, how can there be any delay in between the two actions ? 


Generally this seems to be a dup of https://github.com/sherlock-audit/2023-05-Index-judging/issues/265

Don't see any new information here that would alter the judgement on the original issue.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a valid low based on Sponsor's comment above. 
Agree the there is no clear medium/high impact issue described above

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [saeedalipoorcom](https://github.com/sherlock-audit/2023-05-Index-judging/issues/183/#issuecomment-1612105101): rejected
