### ISSUE TITLE
Saeedalipoor01988 - Trade / addLiquidity transactions lack of expiration timestamp control / slippage check

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#23]
Saeedalipoor01988

high

# Trade / addLiquidity transactions lack of expiration timestamp control / slippage check

## Summary
The Trade / addLiquidity transactions lack of expiration timestamp and slippage control.

## Vulnerability Detail
Let us look into the heavily forked Uniswap V2 contract addLiquidity function implementation

https://github.com/Uniswap/v2-periphery/blob/0335e8f7e1bd1e8d8329fd300aea2ef2f36dd19f/contracts/UniswapV2Router02.sol#L61

// **** ADD LIQUIDITY ****
```solidity
function _addLiquidity(
	address tokenA,
	address tokenB,
	uint amountADesired,
	uint amountBDesired,
	uint amountAMin,
	uint amountBMin
) internal virtual returns (uint amountA, uint amountB) {
	// create the pair if it doesn't exist yet
	if (IUniswapV2Factory(factory).getPair(tokenA, tokenB) == address(0)) {
		IUniswapV2Factory(factory).createPair(tokenA, tokenB);
	}
	(uint reserveA, uint reserveB) = UniswapV2Library.getReserves(factory, tokenA, tokenB);
	if (reserveA == 0 && reserveB == 0) {
		(amountA, amountB) = (amountADesired, amountBDesired);
	} else {
		uint amountBOptimal = UniswapV2Library.quote(amountADesired, reserveA, reserveB);
		if (amountBOptimal <= amountBDesired) {
			require(amountBOptimal >= amountBMin, 'UniswapV2Router: INSUFFICIENT_B_AMOUNT');
			(amountA, amountB) = (amountADesired, amountBOptimal);
		} else {
			uint amountAOptimal = UniswapV2Library.quote(amountBDesired, reserveB, reserveA);
			assert(amountAOptimal <= amountADesired);
			require(amountAOptimal >= amountAMin, 'UniswapV2Router: INSUFFICIENT_A_AMOUNT');
			(amountA, amountB) = (amountAOptimal, amountBDesired);
		}
	}
}
```

```solidity
function addLiquidity(
	address tokenA,
	address tokenB,
	uint amountADesired,
	uint amountBDesired,
	uint amountAMin,
	uint amountBMin,
	address to,
	uint deadline
) external virtual override ensure(deadline) returns (uint amountA, uint amountB, uint liquidity) {
	(amountA, amountB) = _addLiquidity(tokenA, tokenB, amountADesired, amountBDesired, amountAMin, amountBMin);
	address pair = UniswapV2Library.pairFor(factory, tokenA, tokenB);
	TransferHelper.safeTransferFrom(tokenA, msg.sender, pair, amountA);
	TransferHelper.safeTransferFrom(tokenB, msg.sender, pair, amountB);
	liquidity = IUniswapV2Pair(pair).mint(to);
}
```

the implementation has two point that worth noting,

the first point is the deadline check

```solidity
modifier ensure(uint deadline) {
	require(deadline >= block.timestamp, 'UniswapV2Router: EXPIRED');
	_;
}
```

The transaction can be pending in mempool for a long and the trading activity is very time senstive. Without deadline check, the trade transaction can be executed in a long time after the user submit the transaction, at that time, the trade can be done in a sub-optimal price, which harms user's position. The deadline check ensure that the transaction can be executed on time and the expired transaction revert.

In both functions, deadline check by default is block.timestamp–this basically disables the transaction expiration check because the deadline will be set to whatever timestamp the block including the transaction is minted at.

https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/integration/exchange/UniswapV2ExchangeAdapter.sol#L62
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/integration/amm/UniswapV2AmmAdapter.sol#L138

the second point is the slippage control, the slippage control the user can receive the least optimal amount of the token they want to trade.

in the both functions Minimum Receive Quantity is based on the input( Manager ), and there is not any check on the slippage number which does not cause loss or at least not zero. For [Trade ](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/integration/exchange/UniswapV2ExchangeAdapter.sol#L62) function not checked and for [addLiquidity ](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/integration/amm/UniswapV2AmmAdapter.sol#L113):, just check it is lower than liquidityExpectedFromSuppliedTokens.

The slippage Tolerance is set in[ AaveLeverageStrategyExtension.sol contract](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L244), but your [best check and validation](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L936) is :

```solidity
        require (
            _execution.slippageTolerance **<=** PreciseUnitMath.preciseUnit(),
            **"Slippage tolerance must be <100%"**
        );
```

So slippage can set to 100%.

## Impact
The transaction can be exploited by a sandwich attack and cause the above transactions to cause losses.

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/TradeModule.sol#L253
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L433

## Tool used
Manual Review

## Recommendation
protocol add check for slippage and deadline.

**Comment by saeedalipoorcom** [comment]
Escalate for 10 USDC

This is not duplicate of #109 and #304. They discuss about deadline check and suggest to add deadline checker.
This issue is about User (Admin) input which can have a direct impact on the user's transaction.

_execution.slippageTolerance validation is done in the following way, slippageTolerance should be lower **_or equal to 100% ( PRECISE_UNIT = 10 ** 18 )_** :
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L937

```solidity
        require (
            _execution.slippageTolerance **<=** PreciseUnitMath.preciseUnit(),
            **"Slippage tolerance must be <100%"**
        );
```

from [docs.sherlock.xyz](https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-not-considered-valid), **_if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high_**. 

About slippage problem, Sponsor commented that, **_Since this method is called only in the context of operator / manager interactions (as supposed to user interactions), this risk is relatively low._**

But [AaveLeverageStrategyExtension.sol.rebalance() function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L304), has [modifier onlyAllowedCaller(msg.sender)](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/lib/BaseExtension.sol#L140).

About modifier onlyAllowedCaller(msg.sender), Determine if passed address is allowed to call function. **_If anyoneCallable set to true anyone can call_** otherwise needs to be approved.

So there is a scenario / case that anyone can call AaveLeverageStrategyExtension.sol.rebalance() function and it's not only in the context of operator / manager.

Following the slippage problem, the deadline problem can cause harm and lose to the user.

**Comment by 0xffff11** [comment]
Sorry, admin input is not considered an issue. As you pointed out, this is not a duplicate of #109 and it should be invalidated accordingly.

**Comment by saeedalipoorcom** [comment]
> Sorry, admin input is not considered an issue. As you pointed out, this is not a duplicate of #109 and it should be invalidated accordingly.

admin input is not considered an issue if  method is called only in the context of operator / manager. But [AaveLeverageStrategyExtension.sol.rebalance() function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L304), has [modifier onlyAllowedCaller(msg.sender)](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/lib/BaseExtension.sol#L140).

About modifier onlyAllowedCaller(msg.sender), Determine if passed address is allowed to call function. If anyoneCallable set to true anyone can call otherwise needs to be approved.

So there is a scenario / case that anyone can call AaveLeverageStrategyExtension.sol.rebalance() function and it's not only in the context of operator / manager.

So when all users has access to call rebalance function, this is not considered an issue ?

**Comment by 0xffff11** [comment]
According to your explanation and the issue. This case that your are stating allows someone to call this function that is not the admin. But they win nothing from calling this function and they are not really encouraged neither in my understanding. Low

**Comment by hrishibhat** [comment]
Result:
Low
Unique
The slippage tolerance is still set by the admin, others calling the function execute under the same settings. Considering this issue a low.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [saeedalipoorcom](https://github.com/sherlock-audit/2023-05-Index-judging/issues/23/#issuecomment-1611153974): accepted
