### ISSUE TITLE
0x007 - invokeTransfer could cause fund to be lost for tokens that return false and don't revert

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#236]
0x007

high

# invokeTransfer could cause fund to be lost for tokens that return false and don't revert

## Summary
invokeTransfer is used in DebtIssuanceModuleV2 on issue and redeem. invokeTransfer uses setToken to invoke `transfer(address,uint256)` method and it doesn't check the returned data. This could be an issue if token returns false for failed transfer.

## Vulnerability Detail
Some ERC20 tokens return false when transfer or approve fails. They don't revert and it's expected that the caller handles the failure by checking the returned boolean. An example of such token is [ZRX](https://etherscan.io/address/0xE41d2489571d322189246DaFA5ebDe1F4699F498#code).

## Impact
If transfer fail, the transaction would still be successful and token would be minted or burned. Scenarios that could lead to loss of fund
* user that called issue doesn't get debt token
* user that called redeem doesn't get equity token

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModuleV2.sol#L283
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModuleV2.sol#L315
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/lib/Invoke.sol#L66-L78
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/lib/Invoke.sol#L46-L66
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetToken.sol#L197-L212

## Tool used

Manual Review

## Recommendation
If there's returndata from `_setToken.invoke` in `invokeTransfer` and `invokeApprove`, check that it is true and revert if false. `if (returndata.length > 0) require(abi.decode(returndata, (bool)), "ErrMsg");`

Duplicate of #169

**Comment by bizzyvinci** [comment]
Escalate for 10 USDC

This issue as well as #155 are not duplicates of #314.
They are a separate issue that talks about return data checks in the invoke library. The issue is very related to safeTransfer vs transfer methods.
Other duplicates of this issue are #169 and #280

**Comment by bizzyvinci** [comment]
This comment is because I don't think @0xffff11 understands the issue based on his comments on issue [#169](https://github.com/sherlock-audit/2023-05-Index-judging/issues/169#issuecomment-1625656162) and [#280](https://github.com/sherlock-audit/2023-05-Index-judging/issues/280#issuecomment-1622698196).

I aim to explain why #236, #155, #169 and #280 are the same but different from #268 and #314

There are 3 types of ERC20 tokens based on how they handle revert and return data on failed and successful transactions.

| Type | Failure           | Success            | Example |
| ----- | ------------ | --------------- | --------- |
| 1        | Revert           | Return True      | [USDC](https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#code) |
| 2       | Revert           | Return Nothing | [USDT](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#code) |
| 3       | Return False | Return True       | [ZRX](https://etherscan.io/address/0xE41d2489571d322189246DaFA5ebDe1F4699F498#code) |

The current implementation of [invokeTransfer](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/lib/Invoke.sol#L66-L78) and [invokeApprove](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/lib/Invoke.sol#L46-L56) would not work for case 3 because return data from [setToken.invoke](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetToken.sol#L197-L212) is not checked. It would work for case 1 and 2 because they would revert the whole transaction. 

#314 is a very different issue cause it is about approval to 0 or approval race condition
#268 is about case 2 so that's why the [escalation](https://github.com/sherlock-audit/2023-05-Index-judging/issues/268#issuecomment-1611504306) is valid.

It also important to do the fix right, cause if it is done wrongly, then it might cause issue with case 2. Let's check [safeERC20](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.7/contracts/token/ERC20/utils/SafeERC20.sol#L105) as an example. You'll see that they checked for returndata.length first because of case 2 before finally decoding to boolean.
```solidity
function _callOptionalReturn(IERC20 token, bytes memory data) private {
        // We need to perform a low level call here, to bypass Solidity's return data size checking mechanism, since
        // we're implementing it ourselves. We use {Address.functionCall} to perform this call, which verifies that
        // the target address contains contract code and also asserts for success in the low-level call.

        bytes memory returndata = address(token).functionCall(data, "SafeERC20: low-level call failed");
        if (returndata.length > 0) {
            // Return data is optional
            require(abi.decode(returndata, (bool)), "SafeERC20: ERC20 operation did not succeed");
        }
    }
```

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #169

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [bizzyvinci](https://github.com/sherlock-audit/2023-05-Index-judging/issues/236/#issuecomment-1610361789): accepted
