### ISSUE TITLE
tsvetanovv - `mutualUpgrade()` modifier can be bypass

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#246]
tsvetanovv

high

# `mutualUpgrade()` modifier can be bypass

## Summary

`MutualUpgrade.sol` we have modifier `mutualUpgrade()`:
```solidity
modifier mutualUpgrade(address _signerOne, address _signerTwo) { 
        require(
            msg.sender == _signerOne || msg.sender == _signerTwo,
            "Must be authorized address"
        );

        address nonCaller = _getNonCaller(_signerOne, _signerTwo);

        // The upgrade hash is defined by the hash of the transaction call data and sender of msg,
        // which uniquely identifies the function, arguments, and sender.
        bytes32 expectedHash = keccak256(abi.encodePacked(msg.data, nonCaller));

        if (!mutualUpgrades[expectedHash]) {
            bytes32 newHash = keccak256(abi.encodePacked(msg.data, msg.sender));
            mutualUpgrades[newHash] = true;
            emit MutualUpgradeRegistered(newHash);
            return;
        }

        delete mutualUpgrades[expectedHash];

        // Run the rest of the upgrades
        _;
    }
```
This modifier is very important for the protocol and is used in `StreamingFeeSplitExtension.sol` and `BaseManagerV2.sol` contracts which are in audit scope. 

It is used to ensure that it will be called necessarily by two signers (`_signerOne`, `_signerTwo`) and requires the mutual agreement of both before proceeding to action.

## Vulnerability Detail

The modifier can be completely bypassed because didn't check if the same signer from calling the function twice consecutively.

- The first call from the signer will create a hash using the `msg.data` and the address of the other signer (`nonCaller`). This hash will be used as a key to set a flag in the `mutualUpgrades` mapping.
- Now, if the same signer makes the exact same call again, the system will again create the same hash as in the first call because the `msg.data` is the same (same function and parameters) and the `nonCaller` is the same. The system will see that the flag is already set in the `mutualUpgrades` mapping for this hash and will proceed to the deletion of the flag in `mutualUpgrades` mapping and execution of the code denoted by `_`.

This is a serious vulnerability. One signer can execute actions without the consent of the other, defeating the purpose of the two-signer control mechanism.

## Impact

The requirement of having two different signers approve an action is effectively bypassed.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/lib/MutualUpgrade.sol#L41-L67

## Tool used

Manual Review

## Recommendation

You could implement a mechanism to store and check the address of the signer who initiated each action. For example, you could use an additional mapping to store the initiator's address for each action. Before an action is performed, you could check that the initiator is not the same as the current caller.

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

This is a valid issue. I've explained how one signer can bypass the other. So the modifier doesn't work what it was designed for. No single signer should be able to execute a function that requires multiple signatures without the explicit approval of the other required signers.

**Comment by 0xffff11** [comment]
I think the issue is invalid but I can't tell 100 % due to missing some context. @ckoopmann  Thoughts on this one?

**Comment by cvetanovv** [comment]
According to you, what exactly is invalid?

**Comment by JJtheAndroid** [comment]
This issue should be invalid IMO because the contract is out of scope

**Comment by cvetanovv** [comment]
Especially I have verified that it is used in functions that are in scope, which makes the functions themselves vulnerable and does not protect what it is intended for.

For example `setManager()` is in scope:

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/manager/BaseManagerV2.sol#L212-L221
```solidity
/**
     * MUTUAL UPGRADE: Update the SetToken manager address. Operator and Methodologist must each call
     * this function to execute the update.
     *
     * @param _newManager           New manager address
     */
    function setManager(address _newManager) external mutualUpgrade(operator, methodologist) {
        require(_newManager != address(0), "Zero address not valid");
        setToken.setManager(_newManager);
    }
```

We can read what NatSpec says: 
> Update the SetToken manager address. Operator and Methodologist must each call this function to execute the update.

The same applies to the bottom two functions:

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/manager/BaseManagerV2.sol#L251-L290
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/manager/BaseManagerV2.sol#L425-L437

The functions above are extremely important to the protocol, but because the modifier doesn't do what it's intended to do, it makes them very vulnerable.

**Comment by Evert0x** [comment]
This seems like a valid issue to me, @0xffff11 wdyt?

**Comment by 0xStalin-eth** [comment]
@Evert0x , as pointed out by @JJtheAndroid , the contract where the actual vulnerability is reported is out of scope.
![image](https://github.com/sherlock-audit/2023-05-Index-judging/assets/42941728/f60a5ce8-47c9-4eff-ac4b-228ea98de170)

Even if what's reported on this issue is a real vulnerability, unfortunately, the contract where the modifier is implemented it's out of scope.

**Comment by cvetanovv** [comment]
As I wrote above **actual vulnerability** happens in [BaseManagerV2.sol](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/manager/BaseManagerV2.sol) which is in the scopе.
By itself is absolutely no modifier does not drive to vulnerability. Where **actual vulnerability** happens is where it is used.

`setManager()` is in scope:
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/manager/BaseManagerV2.sol#L212-L221
```solidity
* MUTUAL UPGRADE: Update the SetToken manager address. Operator and Methodologist must each call
     * this function to execute the update.
     *
     * @param _newManager           New manager address
     */
    function setManager(address _newManager) external mutualUpgrade(operator, methodologist) {
        require(_newManager != address(0), "Zero address not valid");
        setToken.setManager(_newManager);
    }
```

`authorizeExtension()` is in scope:
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/manager/BaseManagerV2.sol#L251C1-L268

```solidity
function authorizeExtension(address _module, address _extension)
        external
        mutualUpgrade(operator, methodologist)
    {
        require(protectedModules[_module].isProtected, "Module not protected");
        require(!protectedModules[_module].authorizedExtensions[_extension], "Extension already authorized");
        _authorizeExtension(_module, _extension);
        emit ExtensionAuthorized(_module, _extension);
    }
```

`revokeExtensionAuthorization()` is in scope:
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/manager/BaseManagerV2.sol#L270-L290
```solidity
function revokeExtensionAuthorization(address _module, address _extension)
        external
        mutualUpgrade(operator, methodologist)
    {
        require(protectedModules[_module].isProtected, "Module not protected");
        require(isExtension[_extension], "Extension does not exist");
        require(protectedModules[_module].authorizedExtensions[_extension], "Extension not authorized");

        protectedModules[_module].authorizedExtensions[_extension] = false;
        protectedModules[_module].authorizedExtensionsList.removeStorage(_extension);

        emit ExtensionAuthorizationRevoked(_module, _extension);
    }
```

The **actual vulnerability** happens in those functions that are in the scope and they are unprotected.

**Comment by 0xStalin-eth** [comment]
But what is the reason for that vulnerability? What it looks like to be an incorrect implementation of a modifier from a contract that is out of scope.

We shouldn't have anything to discuss if that modifier would've been implemented in a contract that is in scope, but the implementation is in a contract that is out of scope. 

I've seen in previous contests that issues have been excluded  if the root cause of the issue is in contracts that are out of scope, even though the issue impacts contract in scope.
- the reason to exclude the issues have been in the name of fairness, most of the Wastons stick to the contracts that are in-scope.


Also, there are times when protocols go to audits without having completed the development of other contracts, by development includes completing features or fixing bugs, that is why some contracts are left out of the scope of the audit.

**Comment by cvetanovv** [comment]
I've only looked at contracts that are in the scope. So I got to the modifier and saw that the above function are unprotected. 
By that logic, if a function uses a deprecated Chainlink or Uniswap or AAVE function then never report it? Immediately I give an example: why in the last year people have been reporting `latestAnswer()` when nobody says that all Chainlink functors should be audited? 
What if someone wants to use `onlyOwner` on OpenZeppelin, but wrote `ownable` and the function is unprotected(I've seen such a High)? What do we think of this vulnerability on OpenZeppelin? -[Link](https://github.com/sherlock-audit/2022-09-harpie-judging/blob/main/010-M/1-report.md). 
It is obvious that 3 important functions that are in the audit scope are unprotected. 

Тhe **real vulnerability** happens in the functions that are in the audit scopes.

I'm stopping writing in the thread because it just dilutes it, and it's obvious that the above functions completely enter the scopes and are unprotected.

**Comment by 0xStalin-eth** [comment]
The issues reported about Chainlink is not about an incorrect implementation of the function itself, it is an incorrect implementation of the interaction wit such a function, those are two very different things.

One thing is an incorrect implementation of a function, and another completely different thing is an incorrect implementation to interact with a function.

**Comment by ckoopmann** [comment]
While I'd consider this in scope, the observation is incorrect.
Note that the function sets the flag based on the hash computed  with the `msg.sender` address:
```
            bytes32 newHash = keccak256(abi.encodePacked(msg.data, msg.sender));
            mutualUpgrades[newHash] = true;
 ```
 
 Therefore if you call it twice from the same address all that will happen is that the same code (inside the if satement) is executed again (since the if statement is checking the flag for the `nonCaller`), which returns without executing the function body.
 
 The watson probably overlooked that the hash uses different addresses when checking / setting the flag

**Comment by 0xffff11** [comment]
There are 2 things to point out here. 
- The issue is treated as in scope by sponsor
- The issue is actually wrong. Seems that according to last sponsors comment, this can't actually happen due to having the same code executed, which returns on an early return, not executing the whole function.

I think the escalation should be rejected according to last comment

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
This is a non-issue based on Sponsor's comment

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cvetanovv](https://github.com/sherlock-audit/2023-05-Index-judging/issues/246/#issuecomment-1610092461): rejected
