### ISSUE TITLE
jprod15 - The transfer fails if the token does not comply with the ERC-20 standard.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#250]
jprod15

medium

# The transfer fails if the token does not comply with the ERC-20 standard.

## Summary
Tokens like USDT don’t work because they don’t comply with the ERC-20 standard and they don’t return true or false.
## Vulnerability Detail
Tokens like USDT don’t work because they don’t comply with the ERC-20 standard and they don’t return true or false.return true o false
## Impact
trasnfer will revert 
## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/lib/Invoke.sol#L75

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/lib/Invoke.sol#L54
## Tool used

Manual Review

## Recommendation
use safe from openzepelling

**Comment by Shogoki** [comment]
Escalate for 10USDC 
This is not a valid duplicate, as it is about unchecked return values, not approval race condition protection.
Moreover the described impact is invalid, as the transfer would not revert because of this, as the return value from the lowlevel call is never used

**Comment by jesusrod15** [comment]
Maybe this is not a duplicate of 314, but it is a valid issue because it fails due to functionCallWithValue() using this function from OP to check if the return value is success: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f29307cfe08c7d76d96a38bf94bab5fec223c943/contracts/utils/Address.sol#L186-L204. Therefore, it fails.

**Comment by bizzyvinci** [comment]
Most ERC20 including USDT reverts on failures and that's the expected behaviour in that contract cause It doesn't check the return data at all. OZ https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f29307cfe08c7d76d96a38bf94bab5fec223c943/contracts/utils/Address.sol#L186-L204 checks status of low-level call which would be true on success and false on revert. The unchecked data is the returned value from the method e.g ERC20 compliance True or False.

**Comment by Shogoki** [comment]
Agree, there is no revert happening, unless the transfer itself reverted. Which is expected behaviour of course

**Comment by 0xffff11** [comment]
Agree with comments. Despite understanding what watson meant, he does not understand the issue and the actual written report is not right. Escalation should be accepted ,deduplicated and invalid.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique 
Agree with above comments that this is a non-issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Shogoki](https://github.com/sherlock-audit/2023-05-Index-judging/issues/250/#issuecomment-1611513454): accepted
