### ISSUE TITLE
ShadowForce - aave borrow and supply caps can lead to functions reverting

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#267]
ShadowForce

medium

# aave borrow and supply caps can lead to functions reverting

## Summary
aave borrow and supply caps can be breached
## Vulnerability Detail
https://docs.aave.com/developers/whats-new/supply-borrow-caps
in the aave protocol, some assets have borrow or supply caps. Borrowing or supplying beyond this cap is not possible.
this is a problem in this protocol. 
```solidity
    function lever(
        ISetToken _setToken,
        IERC20 _borrowAsset,
        IERC20 _collateralAsset,
        uint256 _borrowQuantityUnits,
        uint256 _minReceiveQuantityUnits,
        string memory _tradeAdapterName,
        bytes memory _tradeData
    )
        external
        nonReentrant
        onlyManagerAndValidSet(_setToken)
    {
        // For levering up, send quantity is derived from borrow asset and receive quantity is derived from
        // collateral asset
        ActionInfo memory leverInfo = _createAndValidateActionInfo(
            _setToken,
            _borrowAsset,
            _collateralAsset,
            _borrowQuantityUnits,
            _minReceiveQuantityUnits,
            _tradeAdapterName,
            true
        );

        _borrow(leverInfo.setToken, leverInfo.lendingPool, leverInfo.borrowAsset, leverInfo.notionalSendQuantity);

        uint256 postTradeReceiveQuantity = _executeTrade(leverInfo, _borrowAsset, _collateralAsset, _tradeData);

        uint256 protocolFee = _accrueProtocolFee(_setToken, _collateralAsset, postTradeReceiveQuantity);

        uint256 postTradeCollateralQuantity = postTradeReceiveQuantity.sub(protocolFee);

        _deposit(leverInfo.setToken, leverInfo.lendingPool, _collateralAsset, postTradeCollateralQuantity);

        _updateLeverPositions(leverInfo, _borrowAsset);

        emit LeverageIncreased(
            _setToken,
            _borrowAsset,
            _collateralAsset,
            leverInfo.exchangeAdapter,
            leverInfo.notionalSendQuantity,
            postTradeCollateralQuantity,
            protocolFee
        );
    }
```
in the snippet above, the `lever` functions works by first borrowing an asset from aave, this asset is then swapped for the target token and later sent to a pool in this protocol. The problem arises when the AAVE borrow cap has been reached. Because the lever function must first borrow, if the AAVE borrow cap has been, the tx will revert and user will not be able to increase leverage in his position,

inversely this is also present in the `delever` although this deals with supply cap instead of borrow cap.
Let us assume that the supply cap is reached, delever function will not execute and revert because AAVE cannot accept more tokens once the supply cap is reached
## Impact
Because AAVE utilizes supply and borrow caps, when the supply cap is reached this will cause delever to revert. When borrow cap is reached, this will cause lever to revert. A user who wants to delever to avoid a liquidation will not be able to and essentially forced into a liquidation. This is a complete loss of funds for the user.
## Code Snippet
https://github.com/IndexCoop/index-protocol/blob/86be7ee76d9a7e4f7e93acfc533216ebef791c89/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L252
## Tool used

Manual Review

## Recommendation
we recommend logic is added that is not reliant on AAVE borrow and supply caps.

**Comment by Jiaren-tang** [comment]
Escalate for 10 USDC. Want to politely ask to make this issue as a duplicate of https://github.com/sherlock-audit/2023-05-Index-judging/issues/10

**Comment by chrisckwong821** [comment]
> Escalate for 10 USDC. Want to politely ask to make this issue as a duplicate of #10

I would like to argue differently since https://github.com/sherlock-audit/2023-05-Index-judging/issues/10 focuses on: 

1. impact of various protocol maintenance function being halted during a cache of twapLeverageRatio
2. twapLeverageRatio is triggered during rebalance.

In this issue there is no mentioning of rebalance and the possibility state it would bring with cache. The only common theme is the mentioning of supply cap. I would rather think this can be a separate issue though, if a failure to supply/withdraw from/to the protocol due to Aave limitation is acceptable submission.

**Comment by ckoopmann** [comment]
Generally it is a known limitation of the protocol that we won't be able to issue new tokens or lever up when the `supplyCap` is reached. In this case no user funds should be at risk though since being "underleveraged" poses no risk of liquidation.

However this should not affect `delever` since in that function we only return previously borrowed tokens and withdraw supplied tokens, so no cap should stop that from functioning.
If the watson could prove me wrong on this second statement, then this would be a valid issue.

**Comment by hrishibhat** [comment]
@Jiaren-tang 
Do you have further comments on this one?

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low. Agree with Sposnor comment above 
https://github.com/sherlock-audit/2023-05-Index-judging/issues/267#issuecomment-1630108823

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShadowForce](https://github.com/sherlock-audit/2023-05-Index-judging/issues/267/#issuecomment-1610130515): rejected
