### ISSUE TITLE
bitsurfer - Unable to update `StreamingFee` to Max Fee config

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#276]
bitsurfer

medium

# Unable to update `StreamingFee` to Max Fee config

## Summary

Unable to update `StreamingFee` to Max Fee

## Vulnerability Detail

In the StreamingFeeModule.sol module, the `initialize()` function is invoked by the Set Manager to configure the initial settings for fees using the `FeeState`. One of the important conditions within this function is to ensure that the `streamingFeePercentage` is below or equal to the `maxStreamingFeePercentage`, which is a logical requirement to maintain consistency and prevent excessive fees.

```js
File: StreamingFeeModule.sol
117:     function initialize(
118:         ISetToken _setToken,
119:         FeeState memory _settings
120:     )
121:         external
122:         onlySetManager(_setToken, msg.sender)
123:         onlyValidAndPendingSet(_setToken)
124:     {
...
127:         require(_settings.streamingFeePercentage <= _settings.maxStreamingFeePercentage, "Fee must be <= max.");
...
133:     }
```

The issue lies within the `updateStreamingFee()` function of the StreamingFeeModule.sol module. Currently, the function only checks if the `_newFee` is below the `maxFee`, whereas it should also allow for equality. This inconsistency can lead to potential discrepancies and limitations when updating the streaming fee, as it restricts the fee from being set at the maximum value allowed by the `maxFee`. It is recommended to modify the condition in the `updateStreamingFee()` function to allow the `_newFee` to be below or equal to the `maxFee`.

```js
File: StreamingFeeModule.sol
150:     function updateStreamingFee(
151:         ISetToken _setToken,
152:         uint256 _newFee
153:     )
154:         external
155:         onlySetManager(_setToken, msg.sender)
156:         onlyValidAndInitializedSet(_setToken)
157:     {
158:         require(_newFee < _maxStreamingFeePercentage(_setToken), "Fee must be less than max");
...
164:     }
```

Indeed, there is an issue in the `updateStreamingFee()` function where the Set Manager may not be able to set the fee to the maximum value specified by the `maxFee` parameter, as it only allows fees below the `maxFee`. This limitation prevents the Set Manager from fully utilizing the maximum fee range that was initially set in the `initialize()` function.

A simple case scenario:

1. Set manager initialize the fee with `maxFee` to 1% and `currentFee` to 0%
2. Later Set manager want to change the fee to its max, the 1%
3. It will failed since the `updateStreamingFee` is reverting the `newFee`

## Impact

This can potentially impact the revenue generated by the protocol, as the fees collected may not reach their intended maximum level.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/StreamingFeeModule.sol#L158

```js
File: StreamingFeeModule.sol
150:     function updateStreamingFee(
151:         ISetToken _setToken,
152:         uint256 _newFee
153:     )
154:         external
155:         onlySetManager(_setToken, msg.sender)
156:         onlyValidAndInitializedSet(_setToken)
157:     {
158:         require(_newFee < _maxStreamingFeePercentage(_setToken), "Fee must be less than max");
...
164:     }
```

## Tool used

Manual Review

## Recommendation

The condition check in the `updateStreamingFee()` function should be modified to allow the `newFee` to be below or equal to the `maxFee`, enabling the Set Manager to set the fee to its maximum value as intended.

```diff
File: StreamingFeeModule.sol
150:     function updateStreamingFee(
151:         ISetToken _setToken,
152:         uint256 _newFee
153:     )
154:         external
155:         onlySetManager(_setToken, msg.sender)
156:         onlyValidAndInitializedSet(_setToken)
157:     {
--           require(_newFee < _maxStreamingFeePercentage(_setToken), "Fee must be less than max");
++           require(_newFee <= _maxStreamingFeePercentage(_setToken), "Fee must be less or equal than max");
...
164:     }
```

**Comment by 0xbitsurfer** [comment]
Escalate for 10 USDC

This is a clear issue which might be missed because it's too simple to be noticed therefore skipped, please reread again judge. In short the `updateStreamingFee` can't set fee to its max due to incorrect logic.

The case provided, if Set Manager unknowingly and generously set an initial 0% fee and 1% max for a set, then he can't update it to 1%, I assume because of this judge may think that this is an input validation issue, but it's not. 

This is an overlooked issue on how a fee can't be updated to max fee. If Set Manager configure with 10% initial and max fee in the beginning, then update to 5%, later if they want to change back to 10% again it will be failed, while it shouldn't. Yes, for sure they can update the fee to 9% but that's not what the protocol intended to be. Recalling, the edge case previously exist to show there is potential issue which makes the StreamingFeeModule failed to support the condition which lead to the fee can't be collected (or less than intended).

The similar issue with this, it's not a "fee" but "interest" which was confirmed as a valid issue
- https://github.com/sherlock-audit/2023-01-ajna-judging/issues/96

**Comment by 0xffff11** [comment]
I think this has to be a low, if you can't set the fee to 1% but you can set it to 0.999% as it seems on the code, this should be a low

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is not a valid medium. The initial setting works accordingly
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/StreamingFeeModule.sol#L127C16-L127C16
This impacts only while updating and the impact of the issue is low as pointed by Lead judge.
