### ISSUE TITLE
tsvetanovv - A user calls `ripcord()` to get rewards, but may actually get nothing under certain circumstances

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#283]
tsvetanovv

high

# A user calls `ripcord()` to get rewards, but may actually get nothing under certain circumstances

## Summary

In `AaveLeverageStrategyExtension.sol` we have `ripcord()` function:
```solidity
function ripcord(string memory _exchangeName) external onlyEOA {
        LeverageInfo memory leverageInfo = _getAndValidateLeveragedInfo(
            incentive.incentivizedSlippageTolerance,
            exchangeSettings[_exchangeName].incentivizedTwapMaxTradeSize,
            _exchangeName
        );

        // Use the exchangeLastTradeTimestamp so it can ripcord quickly with multiple exchanges
        _validateRipcord(leverageInfo, exchangeSettings[_exchangeName].exchangeLastTradeTimestamp);

        ( uint256 chunkRebalanceNotional, ) = _calculateChunkRebalanceNotional(leverageInfo, methodology.maxLeverageRatio, false);

        _delever(leverageInfo, chunkRebalanceNotional);

        _updateRipcordState(_exchangeName);

        uint256 etherTransferred = _transferEtherRewardToCaller(incentive.etherReward);

        emit RipcordCalled(
            leverageInfo.currentLeverageRatio,
            methodology.maxLeverageRatio,
            chunkRebalanceNotional,
            etherTransferred
        );
    }
```

This function is intended to reduce the leverage ratio back to the maximum leverage ratio when the current leverage ratio exceeds a certain threshold. This function can be triggered by anyone, but only by externally owned accounts (EOAs).
The caller of ripcord() will receive a reward in Ether.

Particular attention should be paid when the function calls out `_transferEtherRewardToCaller`:

```solidity
392: uint256 etherTransferred = _transferEtherRewardToCaller(incentive.etherReward);
```

## Vulnerability Detail
`_transferEtherRewardToCaller`:
```solidity
function _transferEtherRewardToCaller(uint256 _etherReward) internal returns(uint256) {
        uint256 etherToTransfer = _etherReward < address(this).balance ? _etherReward : address(this).balance;
  
        msg.sender.transfer(etherToTransfer); 
  
        return etherToTransfer;
    }
```

This function transfers ETH reward to the caller of the ripcord function. If the ETH balance on this contract is less than the required incentive quantity, then transfer the contract balance instead to prevent reverts.

Now let's imagine the following situation as the numbers are just an example:

- Alice calls `ripcord()` in order to receive rewards
- `ripcord()` calls `_transferEtherRewardToCaller()`
- The `_transferEtherRewardToCaller()` calculates that there are fewer ETH rewards in the contract than Alice should receive. Let's say Alice should receive 5 ETH and there are 4 ETH in the contract.
- And in this situation sends the entire ether balance of the contract.

And here come the two possible scenarios.
- It is possible for an Operator to see Alice's transaction in mempool and call [withdrawEtherBalanc()](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L580-L585) before Alice's transaction finishes and withdraw all ETH balance from the contract.
```solidity
function withdrawEtherBalance() external onlyOperator noRebalanceInProgress {
        msg.sender.transfer(address(this).balance); 
    }
```
- But let's say the Operator will never do that. The exact same situation is likely to become completely accidental. And Alice will get 0 ETH. 

## Impact

A user calls `ripcord()` to get ETH rewards but gets nothing.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L368-L400
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1218-L1224
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L580-L585

## Tool used

Manual Review

## Recommendation

You can check if the contract balance is 0 to revert the transaction because `withdrawEtherBalance()` withdraw all Ether from the contract. The other variant is to refactor `_transferEtherRewardToCaller` if the rewards are more than the contract balance to revert the transaction.

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

I have explained how a user can lose eth. One option is if the Operator does it intentionally (which I think is out of scope). 
The other option, however, is that it can happen even if the Operator is a well-meaning and unsuspecting user of ETH loss

**Comment by saeedalipoorcom** [comment]
I don't know why this issue is Excluded by the judge without consulting the protocol or the 0x52 ,Lead Senior Watson.

Dev team commented on the [_transferEtherRewardToCaller function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1212) :
If the ETH balance on this contract is less than required incentive quantity, then **transfer contract balance instead to prevent reverts.**

The [ripcord function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L376) is external and anyone can calls it.

Why should the user who trusted the project suffer a loss?

The simplest scenario for this issue #104 :

- After EOA makes the call to the ripcord function, in return for a reward, the contract will send ETH to the EOA. 
- But the user will get all rewards only if the user's reward is less than the contract balance. 
- so if the user reward is 0.3 ETH and the contract balance is 0.2 ETH, the user will get only 0.2 ETH and 0.1 ETH get lose.

A solution that the project can implement to prevent user loss and reverts, is store the unpaid part of the user's reward so the user can claim it in the future.

It is a security problem that needs to be fixed unless the development team has decided not to make any changes to the code. Watson has recognized it well. The decision of the protocol development team should not make Watson's effort in vain.

**Comment by hildingr** [comment]
How is a user losing ETH? The reward is an incentive to pull the ripcord. Receiving no reward is not stealing from the user it simply is not incentivizing them to pull it. It is up to the operators to keep the reward filled up to incentivize this functionality. 

A MEV bot will most likely always get this reward on chains where MEV is possible. This is not stealing from users that also call this function it is simply somebody else getting there first. From the perspective of the protocol and all its user's the goal is simply to get the ripcord pulled.

**Comment by saeedalipoorcom** [comment]
```
     * Transfer ETH reward to caller of the ripcord function. If the ETH balance on this contract is less than required
     * incentive quantity, then transfer contract balance instead to prevent reverts.
```
**Sorry sherlock** 

> How is a user losing ETH? The reward is an incentive to pull the ripcord. Receiving no reward is not stealing from the user it simply is not incentivizing them to pull it. It is up to the operators to keep the reward filled up to incentivize this functionality.
> 
> A MEV bot will most likely always get this reward on chains where MEV is possible. This is not stealing from users that also call this function it is simply somebody else getting there first. From the perspective of the protocol and all its user's the goal is simply to get the ripcord pulled.

When you solve a security problem in Sherlock competitions, you will be awarded a prize. For example, $100. Does Sherlock have the right to reward you with $50 instead of $100?

I think you should read docs again ! [click to read](https://docs.indexcoop.com/index-coop-community-handbook/products/flexible-leverage-indices/fli-technical-documentation/fli-product-parameters#ripcord-parameters).

Ripcord Parameters act as a last line of defense for investors by protecting against liquidation. **The ripcord function is publicly callable and incentivized by an ETH reward so that anyone can initiate** deleveraging if a FLI product is operating outside the bounds of its safe leverage ratio.

- A user want to help project by calling The [ripcord function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L376). 

- user first check how much reward he will get ! Therefore the user sees the reward amount from [getIncentive ](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L735)function. Reward is 0.1 ETH, it is beneficial for the user and he decides to call ripcord function based on 0.1 ETH.

```
    struct IncentiveSettings {
        uint256 etherReward;                             // ETH reward for incentivized rebalances
        uint256 incentivizedLeverageRatio;               // Leverage ratio for incentivized rebalances
        uint256 incentivizedSlippageTolerance;           // Slippage tolerance percentage for incentivized rebalances
        uint256 incentivizedTwapCooldownPeriod;          // TWAP cooldown in seconds for incentivized rebalances
    }

```
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L203

- At the end, [_transferEtherRewardToCaller function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L392) gets called with incentive.etherReward as input. But contract balance is 0.05 ETH, so user should get 0.05 ETH instead of 0.1 ETH.

Isn't this an abuse of the user's trust? Hasn't the user lost 0.05 ETH of the reward amount here ?

**Comment by hildingr** [comment]
We are not talking about users. This is an external function that will most likely be called by MEV bots first. The protocols only concern is to keep the reward high enough to incentivize this call.

**Comment by saeedalipoorcom** [comment]
> We are not talking about users. This is an external function that **will most likely be called by MEV bots first.** The protocols only concern is to keep the reward high enough to incentivize this call.

**Probability**. is there guarantee that the user will not call this function? this function has onlyEOA modifier. So normal user can also call this function. It is true ?

My recommendation is just a suggestion. The sponsor can ignore this issue, same as #262 and #159. The main issue is that when the contract does not have enough balance to reward the user, it should not allow function ripcord to be called. The result of this incident is explained above.

**Comment by hildingr** [comment]
> > We are not talking about users. This is an external function that **will most likely be called by MEV bots first.** The protocols only concern is to keep the reward high enough to incentivize this call.
> 
> **Probability**. is there guarantee that the user will not call this function? this function has onlyEOA modifier. So normal user can also call this function. It is true ?
> 
> My recommendation is just a suggestion. The sponsor can ignore this issue, same as #262 and #159. The main issue is that when the contract does not have enough balance to reward the user, it should not allow function ripcord to be called. The result of this issue is explained above.

MEV bot can control an EOA. There is no guarantee but when there is free ether for calling a function a MEV bot usually captures it. 

Not allowing the ripcord to be called could be disastrous, even if there is no ether to reward anybody from the Index team or a user of the protocol is incentivized to call it even with 0 reward if the positions is over-leveraged. I highly advice against blocking ripcord when no ether is available this function must always be callable when the leverage ratio is high enough.

**Comment by saeedalipoorcom** [comment]
Why do you complicate the issue? 🙂 sponsor can make any decision for this issue. to fix or not to fix. 🤷‍♂️ 

Ripcord Parameters act as a last line of defense for investors by protecting against liquidation. The ripcord function is **publicly callable** and **incentivized by an ETH reward** so that **anyone** can initiate deleveraging. 

The [_validateRipcord ](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L983)check that should Ripcord be called or not? So, Ripcord function is called only if needed.

- This function is public and any USER or INDEX TEAM or MEV bot can call it with EOA. Transaction fees are not always cheap.

- For calling this function, the user is [promised a reward](https://docs.indexcoop.com/index-coop-community-handbook/products/flexible-leverage-indices/fli-technical-documentation/fli-product-parameters#ripcord-parameters) corresponding to the value of [etherReward](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L121).

`When you solve the security problem in Sherlock competitions, you will be awarded a prize. For example, $100. Is it right to be rewarded $50 instead of $100 for insufficient balance?` 🙂

`In a smart contract, the user stakes his Ethereum. The contract promises the user 10% profit for 1 year. at the end, due to a limitation or miscalculation in the contract, the user will be awarded 5% interest. The user has not lost his fund, but he has lost part of the promised prize. As an auditor, do you consider this a security issue for the user or not?`🙂

Based on the code now in the AaveLeverageStrategyExtension.sol contract, it is possible that the user will not receive the promised reward. If this issue will not occur in the AaveLeverageStrategyExtension.sol, then this issue is invalid.

**Comment by hildingr** [comment]
I believe you made a recommendation that would be dangerous and simply stated it. The escalation period is for discussing issues and escalation, right? I will let the judges take it from here.

**Comment by saeedalipoorcom** [comment]
My recommendation is just a suggestion.same as #262, to add checks to ensure the sequencer is not down, it can be ignored 😊.

**Comment by cvetanovv** [comment]
Imagine you are a user. You see that you will get a good reward. You decide to take the reward and make the transaction. You get 0 rewards. How will you feel: positive or negative? What if this happens to 1000 different users? 

I know Sherlock won't pay a bounty for what the user experience is. But they are losing money and being misled by calling `ricord()`. And for me the problem is not exactly in `ripcord()`, but in [_transferEtherRewardToCalle](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1218-L1224). When they don't get the given reward, at least they can revert the transaction to have a refund of the gas.

**Comment by saeedalipoorcom** [comment]
> Imagine you are a user. You see that you will get a good reward. You decide to take the reward and make the transaction. You get 0 rewards. How will you feel: positive or negative? What if this happens to 1000 different users?
> 
> I know Sherlock won't pay a bounty for what the user experience is. But they are losing money and being misled by calling `ricord()`. And for me the problem is not exactly in `ripcord()`, but in [_transferEtherRewardToCalle](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1218-L1224). When they don't get the given reward, at least they can revert the transaction to have a refund of the gas.

In the **worst** case scenario, the user can receive zero reward. Is the cost of calling ripcord function free? just In the **worst** case.

**Comment by 0xffff11** [comment]
I do not see a user losing funds or whatsoever, it is a public function that anyone can call. As sponsor said mostly for MEV. In the case this function would fail, the user would just have lost gas fees for the transaction if I am not mistaken. Low

**Comment by cvetanovv** [comment]
I did further research and as 0xffff11 wrote the most likely scenario is a loss of gas tax. And he is absolutely right that it would be low severity on almost all chains except Mainnet. But because Mainnet is in the audit scope things went to medium/high severity. Let's do a simple calculation.

Ethereum Avg. Transaction Fee is 4.23$-> [Ethereum Avg. Transaction Fee historical chart](https://bitinfocharts.com/comparison/ethereum-transactionfees.html#3y)

If the function fails to revert in the above scenario 10,000 times (and this is quite real because users will expect to get something, and they actually get nothing), then there will be a loss of user funds of $42,300. What if the protocol is serious and exists for a dozen years and this scenario is repeated 100,000 times. Then the losses would amount to $423,000.

All this can be prevented with the elementary check I have written above.

**Comment by saeedalipoorcom** [comment]
> I did further research and as 0xffff11 wrote the most likely scenario is a loss of gas tax. And he is absolutely right that it would be low severity on almost all chains except Mainnet. But because Mainnet is in the audit scope things went to medium/high severity. Let's do a simple calculation.
> 
> Ethereum Avg. Transaction Fee is 4.23$-> [Ethereum Avg. Transaction Fee historical chart](https://bitinfocharts.com/comparison/ethereum-transactionfees.html#3y)
> 
> If the function fails to revert in the above scenario 10,000 times (and this is quite real because users will expect to get something, and they actually get nothing), then there will be a loss of user funds of $42,300. What if the protocol is serious and exists for a dozen years and this scenario is repeated 100,000 times. Then the losses would amount to $423,000.
> 
> All this can be prevented with the elementary check I have written above.

The problem is that a project can treat users however it wants, and this is not important in the audit process! For example, the contract promises  to user a reward of 100 dollars, but at the end it gives the user a reward of 50 dollars. and the cost that the user pays for the transaction is not considered a loss for the user.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is not a valid high/medium based on the above comments. 
Protocol functions as intended to regardless of whether there is MEV or not.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cvetanovv](https://github.com/sherlock-audit/2023-05-Index-judging/issues/283/#issuecomment-1610798863): rejected
