### ISSUE TITLE
PRAISE - AmmModule.sol's addLiquidity() and addLiquiditySingleAsset() lacks expiration checks

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#29]
PRAISE

medium

# AmmModule.sol's addLiquidity() and addLiquiditySingleAsset() lacks expiration checks

## Summary
addLiquidity() and addLiquiditySingleAsset() functions in AmmModule.sol lacks expiration checks

## Vulnerability Detail
addLiquidity() and addLiquiditySingleAsset() functions doesn't have expiration checks to help revert the transaction in case of network congestions.

Without deadline specified and a deadline checker, the trade could stay in the mempool for a very long time. 

 Network Congestion  situations happens regularly in Mainnet this can cause the transaction to be delayed for a very long time.

## Impact
transactions could be pending in the mempool for a very long time.

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L108

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L155

## Tool used

Manual Review

## Recommendation
implement a deadline and deadline checker like uniswap

**Comment by Love4codes** [comment]
Escalate for 10 USD

I think Amm's like uniswap have deadline and deadline checkers implemented on similar functions for a reason.

**Comment by 0xffff11** [comment]
Not all AMMs have a deadline. Also, please when writing an issue state the impact. A transaction staying on the mempool, is not a valid impact. 

The price moving and because the transactions is still pending the user will get a different amount, possibly getting more slippage, is an impact. 

By the way how you described the issue, this is a low

**Comment by Love4codes** [comment]
boss, is indefinite pending of the transactions due to network congestion not an impact?

i think why i wrote this report this way is because the addLiquidity() function has a slippage protection [here](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L112) so i don't think slippage will be an issue BUT the transaction can remain in the mempool for days, weeks and maybe even possibly months due to network congestion, which isn't ideal.

That's why i gave it a MED

**Comment by Love4codes** [comment]
boss, i have also taken note that not all AMMs have a deadline.

**Comment by 0xStalin-eth** [comment]
@Love4codes you might want to read and get more familiar about the lifecycle of a tx, when TXs are in the mempool they haven't been executed, they are waiting for a validator to pick them up, that's when it comes into play the deadline, for the time when the validator picks up the Tx (if it ever does, because tx can be forever in the mempool) it will validate if the current block.timestamp doesn't exceed the deadline set by the user when it sent the tx

**Comment by Love4codes** [comment]
@stalinMacias noted boss

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
This is a non-issue as it does not clearly describe an issue or its impact.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Love4codes](https://github.com/sherlock-audit/2023-05-Index-judging/issues/29/#issuecomment-1612336133): rejected
