### ISSUE TITLE
Phantasmagoria - Attacker can make some functionality of the protocol completely unusable

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#293]
Phantasmagoria

medium

# Attacker can make some functionality of the protocol completely unusable

## Summary
Attacker can make `removeSet()` function unavailable by creating a lot of setTokens

## Vulnerability Detail
In `SetTokenCreator.sol`, we have the `create()` function, which allows anyone to create a setToken. The newly created setToken is then added to the sets array.
```solidity
sets.push(_setToken);
```

To remove a setToken, the owner should call `removeSet()`. Inside this function, the `remove()` function is called, where `indexOf()` loops over the sets array.
```solidity
(uint256 index, bool isIn) = indexOf(A, a);
```
```solidity
function indexOf(address[] memory A, address a) internal pure returns (uint256, bool) {
        uint256 length = A.length;
        for (uint256 i = 0; i < length; i++) {
            if (A[i] == a) {
                return (i, true);
            }
        }
        return (uint256(-1), false);
    }
```
If the array is large enough, the loop can revert due to running out of gas. As a result, the `removeSet()` function will revert every time,
rendering this part of the protocol unusable.

A malicious user can easily make this array large enough by creating a lot of setTokens. There are no restrictions on anyone creating any amount of setTokens

## Impact
Malicious user can make removeSet() function unusable

## Code Snippet
https://github.com/IndexCoop/index-protocol/blob/86be7ee76d9a7e4f7e93acfc533216ebef791c89/contracts/protocol/SetTokenCreator.sol#L104

https://github.com/IndexCoop/index-protocol/blob/86be7ee76d9a7e4f7e93acfc533216ebef791c89/contracts/protocol/Controller.sol#L178

https://github.com/IndexCoop/index-protocol/blob/86be7ee76d9a7e4f7e93acfc533216ebef791c89/contracts/lib/AddressArrayUtils.sol#L89

https://github.com/IndexCoop/index-protocol/blob/86be7ee76d9a7e4f7e93acfc533216ebef791c89/contracts/lib/AddressArrayUtils.sol#L41-L45

## Tool used

Manual Review

## Recommendation
One way to deal with this issue is to set a limit on how many setTokens can be created

**Comment by Phantasmagoria13** [comment]
Escalate for 10 USDC

I believe this issue is a valid medium issue, as stated in the Sherlock documentation:

> Out of Gas: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or there is a practical call flow that results in OOG can be considered a valid medium or in cases of blocking all user funds forever maybe a valid high. 

You may say that only trusted individuals can create a setToken. However, if we examine the create() function, we can observe that anyone can call it
You can refer to the create() function in this GitHub link: https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/SetTokenCreator.sol#L66-L110
If a setToken were to become malicious or for some reason owner would need to delete it then he would not be able to do so because the removeSet function always reverts. The impact is even more severe because there is no way to undo what the attacker has done

**Comment by IAm0x52** [comment]
Invalid. This short circuits and returns when it matches the token so the function wouldn't be broken because they could just remove entries at lower array indices first bypassing this problem.

**Comment by Phantasmagoria13** [comment]
> Invalid. This short circuits and returns when it matches the token so the function wouldn't be broken because they could just remove entries at lower array indices first bypassing this problem.

But what about tokens that were created later?
For example: 
1. sets array contains 20 settokens. 
2. Then Alice filled up the array with empty tokens(tokens that were created just to fill the array) and now removeSet function reverts
3. After that Bob created new setToken

Now if for some reason admin would need to remove Bob's setToken he will be unable to do so. All tokens that was created after step 2 will be unremoveable as well

**Comment by IAm0x52** [comment]
Assume that indexOf reverts after 400 iterations and there are 20 tokens and 380 empty tokens. It is true that the function cannot remove 400th token directly but if the token being removed is at the 21st index then the function will succeed because indexOf loop will only go through 21 iterations and therefore it won't be DOS'd due to gas. So if the owner wished to remove token 400 then they would remove the lowest index empty tokens until they no longer have a gas DOS.

The other issue here is that in order to reach even the 21M gas cap, the array of set tokens would have to millions long which would surely cost the attacker a huge amount of gas, making this attack unreasonable.

**Comment by Phantasmagoria13** [comment]
Oh that makes sense. Thank you for pointing out my mistake in the previous message. You are right dos attack is not possible. Sorry for any confusion caused by my previous response, and I appreciate your clarification on this matter

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
