### ISSUE TITLE
BugBusters - Index Coop is vulnerable to attackers sending LTV = 0 collateral tokens, supply/supplyCollateral, bor- row and liquidate operations could stop working

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#312]
BugBusters

high

# Index Coop is vulnerable to attackers sending LTV = 0 collateral tokens, supply/supplyCollateral, bor- row and liquidate operations could stop working

## Summary
If a A-Token with LTV==0 is sent to index coop by a malicious user, all the functionalities will halt.
## Vulnerability Detail
When an AToken has LTV = 0, Aave restricts the usage of some operations. In particular, if the user
owns at least one AToken as collateral that has LTV = 0, these operations could revert
1) Withdraw: if the asset withdrawn is collateral, the user is borrowing something, the operation will revert if the
withdrawn collateral is an AToken with LTV > 0
2) Transfer: if the from is using the asset as collateral, is borrowing something and the asset transferred is an
AToken with LTV > 0 the operation will revert
3) Set the reserve of an AToken as not collateral: if the AToken you are trying to set as non-collateral is an
AToken with LTV > 0 the operation will revert

In the attack scenario, the bad actor could simply supply an underlying that is associated with an LTV = 0 AToken
and transfer it to the Index Coop contract. If the victim does not own any balance of the asset, it will be set as collateral
and the victim will suffer from all the side effects previously explained.
While a "normal" Aave user could simply withdraw, transfer or set that asset as non-collateral, Index Coop, with the
current implementation, cannot do it. Because of the impossibility to remove from the Index Coop wallet the "poisoned
AToken", all the mechanics of index coop will break.

## Impact
Above scenerio will have the following impact
1. User will not be able to withdraw, hence cannot de-leverage
2. User will not be able to borrow any asset, hence cannot leverage.
3. Whole mechanism will break, there could be unexpected, liquidation.
4. User will not be able to withdraw if they wanted to.

In short whole system will be doomed

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1-L1274
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L1-L1151

## Tool used

Manual Review

## Recommendation
One probable solution could be to devise a mechanism to remove such poisoned token, probably through the DAO to prevent the centralization risk

**Comment by hildingr** [comment]
Escalate for 10 USDC

This is invalid. 

The warden has copied an issue from another report without understanding how the Index Protocol functions and has therefore outlined an attack that is not possible and has missed the actual vulnerability.

The "poison attack" that the warden has copied from issue 5.1.2 in [this](https://github.com/spearbit/portfolio/blob/master/pdfs/Morpho-Av3-Spearbit-Security-Review.pdf) SpearBit report is not relevant here since transferring aToken to a contract does not automatically activate it as collateral. 

This is a valid issue in Morphio since the same contract is design to have many different collateral activated even if no collateral is deposited.

In the Index protocol this will never be the case. The only way LTV=0 is an issue is when the Index Protocol has another component that owns a collateral that is set to LTV=0, I outlined this #315. The client also agrees that this is the actual issue in [this](https://github.com/sherlock-audit/2023-05-Index-judging/issues/159#issuecomment-1600066030) comment.

This should be invalid, the attack vector is not relevant to Index protocol and has been copied without understanding the difference between Morphio and the Index Protocol.

**Comment by 0xffff11** [comment]
Thanks for escalating it and bringing this out. Indeed seems that you are right and watsons submitted without understanding. Invalid given the good arguments in the escalation.

**Comment by Nabeel-javed** [comment]
Didn't saw the escalation previously, there are few things i want to say. As it have been confirmed by in #159 it is a valid medium in case of transferring the ltv = 0 tokens. Secondly the argument that report is copied, yes it is copied, there are known vulnerabilities and than there are unknown, why in my senses i will write something from scratch when i did my work and read the spearbit repot. Are you guys crying because I did the work to read the report and learn.

Lastly there are alot of other dups too that have same text.

Also just see the https://github.com/sherlock-audit/2023-05-Index-judging/issues/272 and all its dups, most have same text, because such vulnerability have been reported and accepted before. Bashing on both github and discord for learning from a report and making a submission is absurd.

**Comment by Nabeel-javed** [comment]
Discarding this issue mean discarding #159. else it is a valid dup.

**Comment by hildingr** [comment]
I disagree the difference between this report and #159 is that this report has copied an issue without understanding how it related to the protocol. The Vulnerability that you point to does not exist, you have not understood the difference between morphio and Index. The attack vector and recommended solution make no sense for this protocol. 

Compare this to #159 where only the relevant parts have been copied - the consequences on AAVE of LTV=0 token. #159 clearly states "Moreover, LTVs of assets could be set to 0, even though they currently aren't, it could create substantial problems with the potential disruption of multiple functionalities.". There is no mention of the false issue of poison attacks anywhere. 

Comparing this to #272 does not make sense since that is a simple issue that is identical in the previous reports and in this one. This issue is not the same since the protocols differ in how they use AAVE. The sherlock docs state: "Do not copy-paste issues from other contests/reports/past audits. They are extremely unlikely to be valid to the respective contest. ". I argue that this is exactly what happened here.

**Comment by Nabeel-javed** [comment]
Origin of issue is same, if you want to forcefully get it removed, do it. No one getting anything from it. Main issue have same text of morpho report too. Why shouldn't I copy paste the text when issue origin is literally the same. Actually every vulnerability have existed some where in some shape or form, Every one is doing pattern matching 70% of time. But ig common sense is not so common.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique 
This issue does not identify the original issue as identified in #315 & #159. 
This is not forcefully removing it. This issue incorrectly applies the logic of one protocol to another without clearly identifying the issue. 
https://github.com/sherlock-audit/2023-05-Index-judging/issues/159#issuecomment-1600056175

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [hildingr](https://github.com/sherlock-audit/2023-05-Index-judging/issues/312/#issuecomment-1613534019): accepted
