### ISSUE TITLE
0xStalin - Liquidity providers may lose funds when adding liquidity

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#55]
0xStalin

high

# Liquidity providers may lose funds when adding liquidity

## Summary
When adding liquidity there is no protection to prevent that users receive a non-optimal amount of tokens which will end up creating an excess of tokens that won't be redeemable for the amount of LP tokens minted.

## Vulnerability Detail
One of the functionalities in the `AmmModule` contract is to [`addLiquidity()`](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L97-L140) to an AMM pool for a specified AMM.
When adding liquidity to existing Liquidity Pools, all liquidity providers must provide liquidity proportionally to current pool reserves. 
Since a pool is made of two tokens and liquidity is provided in both tokens, there's a possibility for a discrepancy: token amounts may be provided in different proportions. When this happens, [the smaller of the proportions is chosen to calculate the amount of LP tokens minted](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/integration/amm/UniswapV2AmmAdapter.sol#L108-L111)
```solidity
uint256 liquidityExpectedFromSuppliedTokens = Math.min(
    maxTokensIn[0].mul(totalSupply).div(reserveA),
    maxTokensIn[1].mul(totalSupply).div(reserveB)
);
```
As a result, the difference in proportions will create an excess of tokens that won't be redeemable for the amount of LP tokens minted. The excess of tokens gets, basically, donated to the pool: it'll be shared among all liquidity providers of the pool.
While the `_minPoolTokenPositionUnit` argument of the [`addLiquidity()` function](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L112) allows liquidity providers to set the minimal amount of LP tokens they want to receive, it doesn't allow them to minimize the disproportion of token amounts or avoid it at all.

## Impact
Liquidity providers may lose a portion of provided liquidity. While the [`_minPoolTokenPositionUnit`](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L112) protects from slippage when adding liquidity, it doesn't protect from providing liquidity at different K. (x * y = K)

## Code Snippet
- [addLiquidity()](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L108-L140)
- [_executeAddLiquidity()](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L430-L444)
- [getProviderLiquidityCalldata()](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/integration/amm/UniswapV2AmmAdapter.sol#L64-L140)

## Tool used
Manual Review

## Recommendation
- At some point in the addLiquidity flow, consider calculating optimal token amounts based on the amounts specified by user, current pool reserves, and the minimal LP tokens amount specified by user, and make sure to validate if the `optimalAmount is >= minPoolTokenPositionUnit`. As a reference, consider this code from the Uniswap V2 Router: [UniswapV2Router02.sol#L45-L60](https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol#L45-L60).

**Comment by stalinMacias** [comment]
Escalate for 10 usdc

Can I ask the reason why this issue was excluded?

The reported vulnerability is about users losing funds because of not receiving an optimal amount of LPs when adding liquidity.
Uniswap has implemented a solution to prevent this from happening (same solution that I suggest in the recommendation section), so, this is a known issue that occurs when adding liquidity to pools.

Can you help me to understand the reason to exclude this issue?

**Comment by 0xffff11** [comment]
It was excluded because this requires the user to not supply the correct ratio of funds (user mistake) Though I do see that this implementation can be improved and the fix seems reasonable. I would agree to a low

**Comment by stalinMacias** [comment]
@0xffff11 Agree, The finding may not be awarded, but happy to contribute with this finding, end users will be protected from their own mistakes , which usually happens more often than not :)

**Comment by stalinMacias** [comment]
@0xffff11 I did double-think about your comment and I realized that users may be impacted by this issue not necessarily because they made a mistake when supplying the correct ratio.

Let's back to the fundamentals, transactions are not mined immediately (at least in mainnet), they can stay in the mempool for a while until they are included permanently in a block, while the tx is waiting on the mempool an attacker can execute a sandwich attack by depositing more liquidity of one token into the pool which will alter the ratio, and right after the attacker has affected the pool's ratio, the user's tx to deposit liquidity will be executed at an imbalance ratio.

Thus, the user didn't really make a mistake, but an attacker forced the pool's ratio to be imbalanced when the user's tx was executed, thus, the user didn't receive the `optimalAmount` of shares that could've received 


Because of the above explanation and the fact that the Index Protocol is been deployed to mainnet, I'd consider this issue to be at least a valid medium, susceptible to judge & sponsors' decision whether this could be bumped up as a high finding because the impact that it has on LP depositors.

![image](https://github.com/sherlock-audit/2023-05-Index-judging/assets/42941728/b6bae200-42ce-4a96-b935-729177ffa024)

**Comment by Evert0x** [comment]
@0xffff11 any thoughts on the last message?

**Comment by hrishibhat** [comment]
@stalinMacias Despite the sandwich attack mentioned, the LP's would still receive the acceptable amount via `minPoolTokenPositionUnit` right? Maybe not optimal but I don't see it as a loss per se.

**Comment by 0xffff11** [comment]
@stalinMacias as stated by you, to perform a sandwitch here attacker should also deposit liquidity from one token (so neither optimal for him potentially not being profitable either) ?

**Comment by 0xStalin-eth** [comment]
@hrishibhat  Yes, LPs would still receive the `minPoolTokenPositionUnit`, the idea behind this recommendation was to prevent users from always receiving the minimum but instead to ensure they will receive the optimal amount they could've received by adding liquidity.

@0xffff11 Well, actually, the attacker would first deposit in the pool one token to cause the imbalance of the other token, then the tx being sandwiched is executed, and right after that, the attacker deposits back the tokens that it got out of the first transaction.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering the impact of this issue low based on above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [stalinMacias](https://github.com/sherlock-audit/2023-05-Index-judging/issues/55/#issuecomment-1610069399): rejected
