### ISSUE TITLE
0xStalin - All functions that uses the transferFrom() of the ExplicitERC20 library will fail if the token to be transfered is a fee-on-transfer token

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#61]
0xStalin

medium

# All functions that uses the transferFrom() of the ExplicitERC20 library will fail if the token to be transfered is a fee-on-transfer token

## Summary
All erc20 tokens that charge fees on transfer will revert because the strictly equal comparisson to validate if the exact amount of specified quantity was transferred without considering the fees

## Vulnerability Detail
The implementation of the `transferFrom()` in the `ExplicitERC20` library uses a [strict equal check operator to validate that the `post-transferFrom balance is exactly equal to the pre-transferFrom balance + the amount of tokens that were requested to be transferred`](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/lib/ExplicitERC20.sol#L65-L68), the issue is if the token charges fees on the transfer, the actual received amount will be slightly less than what was requested, thus, [the strict equal check will fail, and the whole tx will be reverted](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/lib/ExplicitERC20.sol#L65-L68)

- [Checkout this doc for further reference about fee-on-transfer tokens](https://github.com/d-xo/weird-erc20#fee-on-transfer)

## Impact
All erc20 tokens that charge fees on transfer will revert because the strictly equal comparisson to validate if the exact amount of specified quantity was transferred without considering the fees

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/lib/ExplicitERC20.sol#L43-L70

## Tool used
Manual Review

## Recommendation
Instead of using the current check, update it to validate that the post-transferFrom balance is greater than the pre-transferFrom balance, in this way, if the erc20 charged fees, the tx won't revert
```solidity
function transferFrom(
    IERC20 _token,
    address _from,
    address _to,
    uint256 _quantity
)
    internal
{
    
    if (_quantity > 0) {
        uint256 existingBalance = _token.balanceOf(_to);

        SafeERC20.safeTransferFrom(
            _token,
            _from,
            _to,
            _quantity
        );

        uint256 newBalance = _token.balanceOf(_to);

        // Verify transfer quantity is reflected in balance
        require(
-           newBalance == existingBalance.add(_quantity),
+           newBalance > existingBalance,
            "Invalid post transfer balance"
        );
    }
}
);
```

**Comment by stalinMacias** [comment]
Escalate for 10 usdc

I think for these cases when there is an issue with the README it applies the **Hierarchy of Truth**
As per [Sherlock's Documentation](https://docs.sherlock.xyz/audits/judging/judging#some-standards-observed) **"In case of conflict between information in the README vs Sherlock rules, the README overrides Sherlock rules."**. Whit this in mind I consider my issue to be valid because I audited the codebase based on the rules stated on the README file, which there says that the protocol would be open to know if the protocol can interact with these types of tokens, on the other hand, if in the README would''ve clearly stated that the protocol doesn't intent nor care about these type of tokens, well, in that case, I wouldn't even bother to analyze and determine whether fee-on-transfer tokens could cause issues because the readme is clearly saying that findings reporting problems about that won't be considered valid

![image](https://github.com/sherlock-audit/2023-05-Index-judging/assets/42941728/22f5df31-6fc8-4205-9917-02036eea8853)

**Comment by JJtheAndroid** [comment]
I just wanted to offer my opinion on the matter. In the discord channel, the sponsor clarified that fee-on-transfer tokens issues would not be valid long before the contest ended https://discord.com/channels/812037309376495636/1109133391904915557/1117652312551346176

I don't think it is fair to reward those who didn't read it, knowing that the ones who did refrained from writing any vulnerabilities related to fee-on-transfer tokens

**Comment by stalinMacias** [comment]
I think what @JJtheAndroid  is saying is not a valid point, this boils down to what has the highest weight on the hierarchy of truth. What is stated on the README or what is said in the contest's channel?

I'd kindly propose to Sherlock that the teams can update the README even 5 minutes before the contest starts, and once the contest has started the README gets locked. Otherwise, if messages on the contest channel are taken as the rules then it would be similar to changing the games of a live game, imagine if the rules of an NBA match were changed right in the middle of the game....

**Comment by chainNue** [comment]
agree the README can be seen as the highest weight, so people should stand on this when discords message conflicting the README, but IMO the 
> Not at the moment, but it would be good to know if they can interact with our smart contracts

can be interpreted differently, mentioning my comment on https://github.com/sherlock-audit/2023-05-Index-judging/issues/51#issuecomment-1610671100, so it's up to judge (and protocol team), GL.

**Comment by 0xffff11** [comment]
I don't think sponsor wanted to support fee-on-transfer rather literally just wanted to know. There is always too much confusion with the docs and what you find after on the issues because it is unclear. There has some margin of improvement there. I would still consider the issue low/invalid in this case, but documentation/readme for the audit has to be straight clear, which this one fails to. Note I will bring the discussion further, so Low it is not the final decision

**Comment by hrishibhat** [comment]
Result:
Low
Unique
While the statement in the readme can be open to interpretations, it clearly mentions that the code is not designed to support Fee-On-Transfer tokens in its current state. 
Considering this a low issue.
