### ISSUE TITLE
0xStalin - Can't disengage strategies if the collateral's pool has not enough liquidity

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#62]
0xStalin

medium

# Can't disengage strategies if the collateral's pool has not enough liquidity

## Summary
A malicious third party could cause a DoS to disengage strategies and decrease the leverage or close the position on Aave by forcing no liquidity on the pool by frontrunning tx to disengage and [borrowing the entire pool reserves](https://medium.com/aave/understanding-the-risks-of-aave-43334dbfc6d0#:~:text=This%20situation%20can%20be%20problematic%20if%20depositors%20wish%20to%20withdraw%20their%20liquidity%2C%20but%20no%20funds%20are%20available.)

## Vulnerability Detail
- The logic to disengage strategies and repay the loans is to [withdraw() the collateral from Aave](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L338), and then exchange it for the repayAsset and then repay the debt.

- **AAVE, by design, will lend out all of its reserves, meaning that the amount lent out should not be assumed as liquid.**

- The problem is that an attacker can deny this operation [by borrowing all reserves from AAVE](https://medium.com/aave/understanding-the-risks-of-aave-43334dbfc6d0#:~:text=This%20situation%20can%20be%20problematic%20if%20depositors%20wish%20to%20withdraw%20their%20liquidity%2C%20but%20no%20funds%20are%20available.).
- By borrowing all the reserves from Aave, the withdrawal will fail and the tx to disengage the strategy will be reverted
  - **In a market turndown this can quickly turn open strategies to go below their Liquidation Threshold and cause them to be liquidated on Aave.**
  - The attacker can be incentivized to cause the DoS to cause the strategies to be liquidated on Aave, which will end up making the attacker gain all the collateral of these opened strategies and causing the protocol to accrue losses because strategies were not able to be disengaged
    - The attack can be performed maliciously without the need for a front-run, a sandwich (front-run + back-run) will just make it less costly (less interest paid) for the attacker.

## Impact
By causing a DoS to disengage strategies if the collateral's pool has not had enough liquidity, which could end up causing the positions to be liquidated on Aave

## Code Snippet
- [AaveLeverageStrategyExtension:disengage()](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L412-L438)
- [AaveLeverageModule:delever()](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#LL338C7-L338C7)
- [AaveLeverageModule:deleverToZeroBorrowBalance()](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L407)

## Tool used
Manual Review

## Recommendation
- Think about adding a safeguard path in case the pool has no liquidity. Instead of making the disengage() revert if there is no liquidity, force it to follow the safeguard path.
- The safeguard path could implement a functionality to allow the caller to transfer the amount of tokens required to disengage the strategy, by allowing the caller to transfer the required tokens to repay the debt, the fact that the pool has no liquidity won't prevent the disengage tx to be executed, which will end up reducing the probabilities of an attacker to forcing the pool running out of liquidity.

**Comment by stalinMacias** [comment]
Escalate for 10 usdc

Why was this issue not even considered?

The problem that I'm presenting here is about a malicious user that can deny other users to disengage their positions, by doing this, those positions could fall into a liquidable state and then the same malicious user can go ahead and liquidate the positions of those users who were trying to disengage their positions.

Denying users to disengage their positions is basically tampering with core functionality of the protocol, plus, the consequences are that users' positions can become liquidable. This is not fair for users because they were clearly attempting to prevent their positions to become liquidable, but because the operation was under a DoS now their positions are liquidable (and most likely they will be liquidated, thus users losing their collateral)

The impact of this is user losing their funds, so, can I ask why this issue was excluded?

**Comment by IAm0x52** [comment]
This and #267 are dupes

**Comment by hrishibhat** [comment]
@stalinMacias seems like this is expected behaviour/limitation, do you have a response to the question Sponsor is asking here or do you agree with them?
https://github.com/sherlock-audit/2023-05-Index-judging/issues/267#issuecomment-1630108823

**Comment by 0xStalin-eth** [comment]
Hey @hrishibhat , thanks for the follow-up, I've just checked in detail #267 and realized that my issue and that one is not exactly a dupe of each other.
What I am talking about is a scenario where an external malicious entity (an attacker/mev bot) drains the liquidity of the pool before the tx of the user to disengage the strategy is executed.
- As a result of draining the liquidity on the pool from where the tokens will be withdrawn, the tx will be reverted causing the disengage operation to fail
- DoSing the disengage operation when markets are experiencing big movements is critical because if strategies can't be disengaged they can fall into liquidation.

This is the [flow that a disengage operation follows:](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L403-L406)
> SetToken will redeem collateral position and trade for debt position to repay Aave.

- disengage() => _delever() or _deleverToZeroBalance() => _withdraw() => _executeTrade() => _repayBorrow() => ....

- When running the _withdraw() will attempt to redeem the deposited collateral which then will swap for the token that is owed to finally repay the borrow on AAVE.

- **The problem is if the pool from where the collateral will be redeemed is empty (previously manipulated), the withdrawn collateral won't be enough to repay the specified debt position on AAVE, thus, the whole tx will be reverted.**


> Just as an extra node, AAVE pools by design lend all the available liquidity, so using flashloans it is possible to drain temporarily the funds of the pool from where the collateral would be withdrawn [note](https://medium.com/aave/understanding-the-risks-of-aave-43334dbfc6d0#:~:text=This%20situation%20can%20be%20problematic%20if%20depositors%20wish%20to%20withdraw%20their%20liquidity%2C%20but%20no%20funds%20are%20available.)

**Comment by ckoopmann** [comment]
I agree relying on market liquidity is a limitation of this strategy.

In the same sense as the attack mentioned above an attacker could in theory buy up all of the borrow tokens on all exchanges so that we will never be able to pay back our debt. 
These attacks would be highly costly though since they cannot be done with flashloan and are therefore unlikely to be executed by a rational actor.

I don't think this is an actionable issue for us.

**Comment by 0xStalin-eth** [comment]
Just want to mention that the idea of this attack is applicable when markets are having big movements, the attacker needs to pay the interest on the loan taken on AAVE for just a couple of blocks (just while the disengage tx is executed and then the attacker repays its loan).

The incentive for the attacker will be to liquidate all the accounts that were DoSed asap as they fall into a liquidation state.
- If the liquidation fees for the liquidators are greater than the interests that it would cost to execute the attack, I think this could be considered a valid issue.

The recommendation I'm making about allowing the users to transfer the tokens into the protocol in the event that the withdraw() operation fails would help to prevent the issue I'm talking about.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on the feasibility and impact discussed above in addition to Sponsor comment. 
https://github.com/sherlock-audit/2023-05-Index-judging/issues/62#issuecomment-1653760949

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [stalinMacias](https://github.com/sherlock-audit/2023-05-Index-judging/issues/62/#issuecomment-1610076552): rejected
