### ISSUE TITLE
0xStalin - Removing an enabled borrow asset can be denied

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#63]
0xStalin

medium

# Removing an enabled borrow asset can be denied

## Summary
A malicious user can front-run the tx and send as little as 1 wei of the borrowAsset into the setToken contract, which will make the [check](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L630) to revert, which will cause the removal of the borrowed asset impossible as long as the malicious user continues to front-run the tx to remove the borrowedAsset

## Vulnerability Detail
-  Even though the administrators send a tx to repay the leftover debt before sending the tx to remove the enabled borrowed asset, the malicious user can order the tx so when the tx to remove the borrowed asset is executed, the leftover debt is != 0
- A malicious user can front-run the tx and send as little as 1 wei of the borrowAsset into the setToken contract, which will make the [check](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L630) to revert, which will cause the removal of the borrowed asset impossible as long as the malicious user continues to front-run the tx to remove the borrowedAsset

## Impact
A malicious user can front-run the tx and send as little as 1 wei of the borrowAsset into the setToken contract, which will cause the removal of the borrowed asset to fail

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L624-L636

## Tool used
Manual Review

## Recommendation
The recommendation is to make sure the [`removeBorrowAssets()`](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L624-L636)  is capable of repaying any leftover debt (if there is any), instead of assuming that the remaining debt is 0.

**Comment by stalinMacias** [comment]
Escalate for 10 usdc

Why was this issue excluded?

Consider the scenario where the protocol wants to remove an enabled borrow asset that turns over into a bad asset in the open market and they want to prevent the protocol from being hurt because of that specific asset, malicious users can deny the removal of such an asset, the user can end up being loaded of bad debt because users can continue to take loans of that asset.

**Comment by 0xffff11** [comment]
Does it require the user constantly front-run the transaction, or is it only a 1 timer?

**Comment by IAm0x52** [comment]
Invalid. That check is for the AAVE debt token which you can't transfer to other users.

**Comment by stalinMacias** [comment]
@0xffff11 This requires constantly front-run the transaction, in normal market conditions attacker may not be incentivized to attempt this attack, but in market turbulence when the value of a collateral asset is dropping, malicious users are incentivized to continuously front run the transaction so the `borrowAssets` remains enabled.

@IAm0x52 I may used the incorrect wording, but the malicious user basically need to load 1 wei of debt of the borrow asset, so [the check will fail because is using the strict equal comparisson operator](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L630)

**Comment by IAm0x52** [comment]
@stalinMacias how exactly would they load 1 wei of debt onto the set token? On AAVE each market has two tokens, the debt (variableDebtUSDC) token and the collateral (aUSDC) token. The collateral token can be transferred but the debt token cannot. The check you are referring to is specifically for the variable debt token.

**Comment by stalinMacias** [comment]
@IAm0x52 I think you are right, I may misunderstand something on this portion of the codebase, thanks for the clarification and explanation about the `debtTokens`. Happy to take the L on this escalation 💯

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the comments above.
