### ISSUE TITLE
saidam017 - E-Mode configured using `AaveV3LeverageModule` could make other Module that need to borrow on outside category fail

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#95]
saidam017

medium

# E-Mode configured using `AaveV3LeverageModule` could make other Module that need to borrow on outside category fail

## Summary

If setToken `AaveV3LeverageModule` is set category to any of the `eModeCategories` configured by the `PoolConfigurator`, then the borrowed can only in the chosen category. This could lead to issue if `AaveV3LeverageModule` or other module that interact with Aave and require to borrow asset not in the chosen category.

## Vulnerability Detail

[According to Aave V3 docs](https://docs.aave.com/faq/aave-v3-features#how-does-e-mode-affect-my-borrowing-power) :

"Only assets of the same category (for example stablecoins) can be borrowed in E-mode."

With this behavior, using asset with E-Mode enabled on set Token that have AaveV3Leverage and debt issuance for multiple asset that is outside of the chosen category could not work properly.

For instance, debt issuance rely on borrow when issue a token : 

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModule.sol#L677-L697

```solidity
    function _executeExternalPositionHooks(
        ISetToken _setToken,
        uint256 _setTokenQuantity,
        IERC20 _component,
        bool _isIssue,
        bool _isEquity
    )
        internal
    {
        address[] memory externalPositionModules = _setToken.getExternalPositionModules(address(_component));
        uint256 modulesLength = externalPositionModules.length;
        if (_isIssue) {
            for (uint256 i = 0; i < modulesLength; i++) {
                IModuleIssuanceHook(externalPositionModules[i]).componentIssueHook(_setToken, _setTokenQuantity, _component, _isEquity);
            }
        } else {
            for (uint256 i = 0; i < modulesLength; i++) {
                IModuleIssuanceHook(externalPositionModules[i]).componentRedeemHook(_setToken, _setTokenQuantity, _component, _isEquity);
            }
        }
    }
```

On the other hand, currently no restriction inside `addBorrowAssets()` that it only accept asset in the same category : 

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L627-L629

```solidity
    function addBorrowAssets(ISetToken _setToken, IERC20[] memory _newBorrowAssets) external onlyManagerAndValidSet(_setToken) {
        _addBorrowAssets(_setToken, _newBorrowAssets);
    }
```
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L1120-L1130

```solidity
    function _validateNewBorrowAsset(ISetToken _setToken, IERC20 _asset) internal view {
        require(!borrowAssetEnabled[_setToken][_asset], "Borrow already enabled");

        ( , , address variableDebtToken) = protocolDataProvider.getReserveTokensAddresses(address(_asset));
        require(address(underlyingToReserveTokens[_asset].variableDebtToken) == variableDebtToken, "Invalid variable debt token address");

        (, , , , , , bool borrowingEnabled, , bool isActive, bool isFrozen) = protocolDataProvider.getReserveConfigurationData(address(_asset));
        require(isActive, "IAR");
        require(!isFrozen, "FAR");
        require(borrowingEnabled, "BNE");
    }
```

## Impact

 This could lead to issue if `AaveV3LeverageModule` or other module that interact with Aave and require to borrow asset not in the chosen category.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModule.sol#L677-L697
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L1120-L1130
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L627-L629

## Tool used

Manual Review

## Recommendation

When E-Mode is planned to be configured, add restriction that allowed borrow is only asset in the chosen category of E-Mode.

**Comment by said017** [comment]
Escalate for 10 USDC

I think this issue should be duplicate of #https://github.com/sherlock-audit/2023-05-Index-judging/issues/251

**Comment by stalinMacias** [comment]
I don't think this is a duplicate of #251 , the issue reported here is about the asset's restriction when eMode is activated, and the issue reported on #251 is about the percentages that are used in AAVE for liquidations, those are two totally different things, plus, there is not an impact on users depositing assets if eMode is activated, those assets won't get stuck or lost, they won't simply count as collateral, and that doesn't affect the internal accounting of the setTokens.
Actually, this issue is similar to this #83 , which should also not be a duplicate of #251, and none of these two issues causes damage to the users.

**Comment by said017** [comment]
Then with this logic, #251 is not the also not cause issue because users asset won't stuck, that issue mentioned : 

> It is also worth considering that the set token as well as other integrated modules configurations/settings would assume this higher LTV.

Which is simply not entirely correct because at the end of the day. It still query to Aave pool, which will prevent users/setToken from doing anything harm. At worst, this issue is simply cause user not benefiting the better LTV for E-Mode or The users modules not work at all because the the borrowed assets is not the stablecoins.

This will never harm users and assets won't ever stuck or lost because Aave never allow any such harmful operation in the first place (it will always check the healthy and allowed call via default pool) : 

```solidity
        (, , , , , , bool borrowingEnabled, , bool isActive, bool isFrozen) = protocolDataProvider.getReserveConfigurationData(address(_asset));
```

```solitiy
  DataTypes.ReserveConfigurationMap memory configuration = IPool(ADDRESSES_PROVIDER.getPool())
    .getConfiguration(asset);

  (ltv, liquidationThreshold, liquidationBonus, decimals, reserveFactor, ) = configuration
    .getParams();
```

This issue pointed out that the setup modules will broken and fully support E-Mode, because that is the actual issue, users fund lost or stuck will simply not possible, because Aave healthy check will never that operations.

**Comment by hildingr** [comment]
I don't think your issue makes sense. Obviously depositing assets that are not in the same category will not be used in E-mode. That is why E-mode works in the first place. Not sure what issue you are pointing to? If a manager configures such a SetToken then they simply don't understand the basics of what E-mode is, this is not a vulnerability but a user error. This has nothing to do with #251. I think it is more reasonable to attempt to escalate your issue to a unique since the root of the issue is different. I personally disagree that your issue is valid but you could get a judge to look at it from that perspective.

In regards to #251, the issue found breaks the protocol. The thing it was design for does not work. Other than breaking the protocol it also has multiple consequences outlined in #334 and other duplicates.

**Comment by said017** [comment]
@hildingr, your issue actually brings up a valid point by bringing on the specific `targetLeverageRate`, I think that points out how it would break the assumption that is being made. And to think about it, yes, while it might good to have the guard of list in the same category, my issue tends toward user error category.

Thanks for the enlightenment sir @hildingr @stalinMacias
